### ISSUE TITLE
Improve bower-list or add outdated command

### ISSUE THREAD

**Issue by Anachron** [bower/bower#1138]
Like #955, except that I want better programmatical access. 

I would like to filter only to those packages that are actually outdated.
Everything else is fine, I can parse the resulting data from --json and use it as I wish.

**Comment by jerone** [comment]
:+1:

**Comment by jpaas** [comment]
:+1:

**Comment by Jaitls** [comment]
:thumbsup:

**Comment by beaudesigns** [comment]
Yes please. +1

**Comment by rebelliard** [comment]
:+1:

**Comment by codingsteff** [comment]
+1

**Comment by dlmiles** [comment]
"We cannot provide clear command switch (like --outdated) because there are different types of outdateness (patch version, minor version, major version, security update etc.)."

Maybe you can better explain why the exact types of outdateness matter ?  What is certainly not very useful is the choice of bower to show the latest version no matter what.

The version info in bower.json contains the version limits.  So what is important is:
* Is there a newer version we can download and install that is inside the version limits like "~3"
* What is the very latest version according to semantic versioning (it only does this right now)

So if you care fore major/minor/patchlevel you modify your version limit specification accordingly.

At the moment "bower list" seems to provide only the very latest version, and often this is an alpha/beta/pre-release/snapshot of the next major version being worked on and of little interest when maintaining a project.  Also major versions usually mean breaking changes, again of little interest when maintain a project.

It would be better if "bower list" at least used 2 colours in the output.
* As now, dark-cyan for indicating the very latest version that exists.
* Additionally, dark-red for indicating a newer version that exists, that is also inside the version limits from bower.json (like NPM)

All this info can be displayed together, there is no need to pick which we want displayed.  Colouring the item will indicate this, in the case of no colour in output then the most important info is displayed, that is not the dark-cyan info like now.

Now if there are "security update" version that exists (and you have that info) you display on a separate line, since big fat warning like "SECURITY WARNING foobar#1.2.3 ....".  Again displays as well as the above.

**Comment by bdkent** [comment]
I would love it if there was at least an option to hide the "build/alpha/beta/pre-release/snapshot" style updates. On a large project you quickly end up with more noise than meaningful updates.

**Comment by AdamBarnwell** [comment]
+1

**Comment by thomblake** [comment]
:+1: just make it work like npm

**Comment by Davidiusdadi** [comment]
+1

**Comment by atomless** [comment]
👍

**Comment by renatocarvalho** [comment]
👍

**Comment by sheerun** [comment]
Bower is now deprecated and in maintenance mode which means we won't be adding new features
