### ISSUE TITLE
EPERM error when installing from ZIP file on Windows

### ISSUE THREAD

**Issue by hban** [bower/bower#1176]
Installing from the ZIP file on Windows machine always fails with the `EPERM rename` error.

After some debugging, I have found that the error happens when the ResolveCache tries to rename/move temporary directory where ZIP was extracted to the cache directory.

Edit: See [this comment](https://github.com/bower/bower/issues/1176#issuecomment-38990383) for more details.

System info:
Bower version: 1.3.1
Node version: 0.10.26
OS: Windows_NT 6.2.9200 x64

**Comment by sheerun** [comment]
I've added Windows CI support for bower. I encourage you all to create failing test, so we can fix it.

**Comment by dditomaso** [comment]
I have a basic setup that triggers the bug in a blank project, the setup is like this:

    src/
        bower.json
        .bowerrc

`bower.json`'s contents are:

    {
      "name": "prueba",
      "version": "0.0.0",
      "homepage": "",
      "authors": [
        "presentes"
      ],
      "moduleType": [
        "amd"
      ],
      "license": "GPL",
      "dependencies": {
        "jquery": "*",
        "modernizr":"*"
      }
    }

and I had to add the .bowerrc due to being behind a corporate proxy:

    {
        "registry": "http://bower.herokuapp.com"
    }

Nevertheless I'm worry that is an artifact of being behind a corporate proxy.
Please give me assistance on how to further provide information.

**Comment by sheerun** [comment]
This should be fixed in bower 1.6.2 thanks to https://github.com/bower/bower/commit/0bb1536c9972e13f3be06bea9a8619632966c664
