### ISSUE TITLE
insight-bower.yml gets root privileges if you run as root the first time

### ISSUE THREAD

**Issue by yuvii** [bower/bower#1223]
When I ran bower for the first time, I had to run it as root, i.e. with --allow-root. One of the files it creates on first run is `/home/user/.config/configstore/insight-bower.yml`, and since I ran bower the first time as root, it gave this file root ownership, which seems wrong. But more importantly, it means the next time I tried installing _without_ root permissions, I got an EACESS error. The only solution was to remove the file completely, and let bower recreate it.

**Comment by deepakkaithwas** [comment]
I just fixed it in Windows.
I have done three things, which one have fixed it I am not sure.
1. Run cmd prompt as administrator.
2. takeown /? this command is equivalent to chown (linux) but for windows.
3. cacls -cacls <file or directory> /E /T /G <user>:F
4. simply go in $USER /Users/calvin/.config/configstore/ and make files unhidden.

it worked for me like charm.
I have been trying to fix this since many days.
