### ISSUE TITLE
Svn url prefix wrong

### ISSUE THREAD

**Issue by dika-pro** [bower/bower#1313]
Hello

I want to install via bower my private repo which is hosted on remote server.

Normally i would just do "svn co someurl". But i want little bit of automatism.

```
bower install svn+ssh://myurlr/ticketJs/
```

Doing this will produce error:

```
bower ticketJs#*               ECMDERR Failed to execute "svn list svn-ssh://myurl/ticketJs/tags --verbose", exit code of #1

```

If i do do this manually it is fine

```
svn list svn://myurl/ticketJs/tags --verbose
```

To conclude difference is in url prefix "svn+ssh" != "svn"

**Comment by rodro75** [comment]
Hello @ahmadnassri, I have a very similar problem and I think it's the same bug.

I'm trying to install a test package from my privately hosted svn server, using the **svn** prefix (we only host with svnserve, so no http is possible).

When I run:

`bower install svn://mydomain.it/myRepo/myLibrary#1.0.0`

bower tries to get the list of tags with the command:

`svn list http://myDomain.it/myRepo/myLibrary/tags --verbose --non-interactive`

which is obviously wrong because it's using http!
Am I missing something?
Any feedback would be welcome, thanks.

**Comment by ahmadnassri** [comment]
pinging @vladikoff to help merge that PR

**Comment by vladikoff** [comment]
Ah I see, it might make sense to rebase that Nov 18, 2014 PR. If no one does I'll file a new one and go from there...

**Comment by sheerun** [comment]
Now that Bower is deprecated I'm going to close this issue. If it affects someone 6 years later, please open new issue
