### ISSUE TITLE
Change behavior of resolutions in bower.json

### ISSUE THREAD

**Issue by sheerun** [bower/bower#1362]
The current behavior of `resolutions` key in `bower.json` is really confusing.

It is used only if conflict between dependencies occurs. That means as soon as there's no longer a conflict, the resolutions are ignored. It means bower users are not able to fix component version by specifying it in `resolutions.`. This issue is connected to lack of shrinkwrap feature (#505).

My proposal is following:

Modify the behavior of `resolutions` in backward-compatible way: force given version of component regardless if conflict occurred.

**Comment by Parakleta** [comment]
While you are considering changing the `resolutions` behaviour I think it should be extended to include the path to a package as well as its version.  There appears to be a vulnerability in bower as it stands in that it doesn't expose collisions in package paths, and only considers the version.

Consider the case where you are depending on several other packages which each depend on jquery.  This is all fine and the version requirements are such that there is a common version they all agree on.  Now consider that one of these packages decides to use a fork of jquery (possibly hostile) and they advance their version to a later version that still meets the requirements of your other packages.  Now at the next update bower will pull in the forked version of jquery, and not raise any alert that it is coming from a different repository to the one expected by the other packages.

In this case bower should be raising an alert the same as incompatible versions, and storing the result in the `resolutions` table with the path to the project.

This has the added benefit that users will be able to override dependencies in their projects by specifying a resolution to a fork if that is what they desire.  I am sort of using this by specifying specific commit hashes in my `dependencies` and `resolutions` to override the child-dependencies of sub-packages.  I am forced to use commit hashes (or branches) but not versions because the current `resolutions` doesn't fire if the versions are not incompatible, and I'm not sure how bower resolves multiple dependent repositories with the same version.

**Comment by sheerun** [comment]
Bower is deprecated now, and in maintenance mode. Because of this we won't implement new features like this one. We recommend switching to Yarn or npm, and migrating with [bower-away](https://github.com/sheerun/bower-away)

**Comment by sheerun** [comment]
btw. yarn supports resolutions as well: https://classic.yarnpkg.com/en/docs/selective-version-resolutions/
