### ISSUE TITLE
Auto-sort bower.json dependencies alphabetically?

### ISSUE THREAD

**Issue by lukehorvat** [bower/bower#1373]
I like how, as of late, `npm install --save` automatically re-writes `package.json` so that dependencies are listed in alphabetical order. Makes it easier to visually parse the file, and ensures some consistency across different Node.js projects. That said, I'm sure some folks prefer to have dependencies listed in order of when they were saved, but that's what version control (e.g. `git blame`) is for IMO.

Would be nice to have this feature when doing `bower install --save`. Thoughts?

**Comment by ilanbiala** [comment]
+1 this would be awesome!

**Comment by devdoomari** [comment]
seriously people, don't push for ideas like this...
"alphabetical" may seem good, but looking good shouldn't be an excuse to break things.
npm can do this because none of its toolbox relies on dependency order...
but a lot of tools using bower (e.g. for webpack+gulp with mainbowerfiles) depend on that dependency order because they simply concat files :(

At least, you should've made this off-by-default

**Comment by benschwarz** [comment]
I'm not onboard with this change.

It will cause breaking changes for people who have automated their builds, and I don't believe it to be a legitimate use case. 

Feels cute, but not useful.

**Comment by tystol** [comment]
Another -1 from me. Just spent an hour debugging seemingly random errors until I realized that my bower.json file had changed order, which meant my gulp+wiredep build changed the order of the concatted 3rd-party scripts and put angular before jquery.

**Comment by eburi** [comment]
-1

Same here - gulp+wiredep depends on the order of the dependencies. Now I either have to reorder it after adding a dependency or add stuff manual only.
How can I opt-out?

**Comment by michgeek** [comment]
Go back to bower 1.4.1
`sudo npm install -g bower@1.4.1` for global installation or
`npm install bower@1.4.1`

**Comment by devdoomari** [comment]
@michgeek  that would still be 'break-by-default' for a lot of people using bower with some build tools.

Seriously, this should be off by default...

**Comment by michgeek** [comment]
@devdoomari I agree. Clearly should be off by default.

**Comment by michgeek** [comment]
Finally! Thanks @sheerun

**Comment by sindresorhus** [comment]
If you depend on the dependency order in bower.json you're doing it so wrong... Auto-sorting of dependencies was a nice feature as it enforces consistency. This should not have been reverted!

**Comment by michgeek** [comment]
In which way is it consistent to order it alphabetically? Can you please give a solution that is right? Dependencies in the javascript library ecosystem has always been order sensitive. Why would you bother handling N-more tools and manually maintain another "ordering" array?

**Comment by devdoomari** [comment]
@sindresorhus in that case, how about processing dependency graph & producing a partially-alphabetical order that does not break dependencies?
(e.g. Angular depends on jQuery, but Backbone & react are separate:
Backbone
jQuery
Angular
React
...and so on)
Then it's somewhat 'consistent', and nobody gets a broken builds : )

**Comment by sheerun** [comment]
@michgeek Ideally ordering should be calculated automatically, given dependencies between packages.

**Comment by JaKXz** [comment]
I've been using bower with wiredep for a while and AFAIK the wiredep API returns the list of dependencies in the right order regardless of the order in the `bower.json` because it traverses the dependency tree recursively. I was really surprised to see people having issues with this change... but maybe I'm missing something?

**Comment by devdoomari** [comment]
@JaKXz  I've been using bower-main-files because it's much simpler to do so for my personal get-stuff-done-quickly (don't care about performance/file size/etc.) note there are tools other than wiredep that depends on bower.json

as for wiredep, if it does dependency tree processing, then this change won't break stuff for its users.
but for users who don't want to configure wiredep/etc and use simpler tools like bower-main-files that simply concat files, this change-on-default-behavior is a pain on *somewhere.

**Comment by pribilinskiy** [comment]
-1
Going back to 1.4.1

**Comment by sheerun** [comment]
This has been reverted in 1.5.3

**Comment by chrisdothtml** [comment]
Why was this reverted? I can understand making it disabled by default, but there are clearly people who don't rely on dependency order in their bower.json who could benefit from this (me included). Why not leave it in as optional?

**Comment by sheerun** [comment]
It can be if someone prepares PR with a flag

**Comment by chrisdothtml** [comment]
@sheerun Made one based on the original #2358 

New to the whole contributing world so let me know if anything's off

**Comment by 807811b0-1373-11e5-b60b-1697f925ec7b** [comment]
If your build automation depends on the order of the dependencies in bower.json then there is a bug in your code.

**Comment by osbeug001** [comment]
I also wanted to auto sort my dependencies in my bower.json, it's simply more legible & easy to follow.
I found an npm plugin [fixpack](https://www.npmjs.com/package/fixpack) that works for me.
It can also sort your package.json file too.
