### ISSUE TITLE
--save flag to update bower.json when updating a package

### ISSUE THREAD

**Issue by sephie** [bower/bower#1468]
I like how one can run `$ bower install some-such --save` and have the `bower.json` edited alongside it. 

Unless I'm missing an obvious reason not to, this function could also be handy when performing an `update` to a package dependency, eg. `$ bower update some-such --save`

**Comment by MWalid** [comment]
+1 Same request

**Comment by epsyan** [comment]
+1

**Comment by saschaseewald** [comment]
+1

**Comment by pflannery** [comment]
+1

**Comment by ExplodingCabbage** [comment]
> so what command we should use in the way we ‘d like to, i.e. update the dependencies and update the bower.json with the new packages versions?

    bower install some-package-i-have-already-installed --save

seems to do this just fine (although it's counter-intuitive that 'install' would be the command for this, given that in e.g. npm or Composer or Bundler the nearest equivalent action would be named 'update').

I think the functionality being asked for here already exists, just with an unexpected command name?

**Comment by eliothxchan** [comment]
+1

**Comment by santi8ago8** [comment]
+1

**Comment by AlvaroLazaro** [comment]
+1 Please, give us the opportunity to automatically update all the packages that seem to have a new version (fetched by check-new) and save that versions to bower.json

**Comment by rohitmanglik** [comment]
+1

**Comment by ExplodingCabbage** [comment]
Everyone +1ing this: what's wrong with

```
bower install some-package --save
```

? It seems to me that this updates packages and saves the changes to `bower.json`, which is exactly what you want it to do. @eliothxchan @santi8ago8 @AlvaroLazaro @rohitmanglik, what functionality are you actually missing?

**Comment by rohitmanglik** [comment]
@ExplodingCabbage If I understood it correctly, bower update should work as shown in the attached image. 

Kindly guide me where us where we are/I am missing.

![bower update](https://cloud.githubusercontent.com/assets/677634/7611763/3dbdf120-f9a4-11e4-8d04-8f5467def632.PNG)

**Comment by ExplodingCabbage** [comment]
@rohitmanglik what's wrong with `bower install angular --save`? That will update angular to whatever version you choose and save the new version to `bower.json`.

**Comment by rohitmanglik** [comment]
@ExplodingCabbage sorry, but what command shall I write in this case?

I guess what everyone over here understood was, "bower install angular --save" will update 1.3.15 to 1.4.0.rc.2. It did not ask me what version I want. I guess this is not what to expect (see screenshot).

Does it pick the version from bower.json. Do I need to update bower.json first? 

Sorry for this silly question but, I believe, many people are facing the same issue.

![bower update 1](https://cloud.githubusercontent.com/assets/677634/7612027/be2428d8-f9a5-11e4-99e4-831c2176f9f7.PNG)

**Comment by ExplodingCabbage** [comment]
@rohitmanglik you're right and I'm wrong - apologies. In the cases where I'd used this command in the past, it had just happened to always offer me the latest version, but some experimenting shows that's not always the case. I honestly don't know how to do what people here are asking for (update a library to its latest version from the command line and persist the choice to bower.json).

**Comment by skoczen** [comment]
Via [SO[(http://stackoverflow.com/questions/18105897/update-multiple-dependencies-with-bower), this does it: https://www.npmjs.com/package/bower-update

**Comment by eliothxchan** [comment]
@skoczen

You do realize the entire issue is literally about bower update/install lacking functionality, right? Did you read the posts in this thread?

**Comment by skoczen** [comment]
@eliothxchan I might be a complete idiot, but I'm pretty sure that what I'm referencing is different.

Aka,
```
bower update
```

is not the same as

```bash
npm install bower-update
bower-update
```

If I'm wrong, please correct me.  Otherwise, it might be useful to treat people a bit less bitingly, and read a bit more yourself.

**Comment by nandhakumarr** [comment]
For a single package, I just did a ...
    bower uninstall <package_name> --save
    bower install <package_name> --save

**Comment by eliothxchan** [comment]
@skoczen

We want to bulk update AND persist the changes to bower.json, not simply bulk update.

**Comment by skoczen** [comment]
@eliothxchan I was nice the first time.  Now you're just being an asshat.

Bulk update and persist is *exactly* what the `bower-update` package does.  I know, because I used it today, and it did just that.  And then I tested it again, just now, and it did it again.

There were days, 10 years ago, when programmers could be complete dicks to everyone on the basis that "the most right wins."  People being jerks and lacking basic social skills were tolerated and forgiven in the community.

Those days are gone.  Based on the minimal amount of code and time on your github profile, I'm going to assume you're fairly new to professional coding. So, here's some unsolicited advice that can genuinely help you in your career. (Cred: I've been at this for 20 years, at some amazing places, and it's still going quite well.)

**Be nice to people, and be humble.**

There will be times (like this one) where you're flat out wrong.  Being humble and pleasant means that your colleagues and fellow contributors don't think badly of you for being wrong.  You thought something, learned differently, and grew.  And you were lovely to be around for that whole process. Those are the kinds of people everyone wants to be around.

There will also be times where you're right, and other people are wrong.  By being pleasant and humble, you allow a safe space for *other people* to learn and grow, which makes them respect you more.  It also allows you to become "even more right" by growing your perspective from use cases and edges of knowledge you may not have considered.

Be nice, and be humble.  That's it.

Of course, you're free to go full youtube troll on all this, ignore it, or do whatever you'd like.  

I've said my piece and I won't distract this thread further.

I do hope though, that you give what I said above a few moments of consideration.  It'll make the difference of hundreds of thousands of dollars over your career, and dramatically improve the quality of people you find in your life.

Best of luck.
-Steven

**Comment by migig** [comment]
+1 for the shortcut

**Comment by gnicol-bzh** [comment]
I'm a bit confused with what I read. 

As far as I'm concerned, I was thinking that:
* ```bower install <package-name>``` installs the version specified bower.json *(it may be important on large projects that all the collaborators have exactly the same versions of components)*
* ```bower update <package-name>``` installs the last version available, no matter wich version is specified in bower.json

And for both, ```--save``` would update bower.json (updating version if necessary).

Am I wrong ?

**Comment by tablatronix** [comment]
So sounds like the only solution is to `install --save` for all packages one at time.

**Comment by syzer** [comment]
![most-evil-bower](https://cloud.githubusercontent.com/assets/1989646/10512021/ab66a2b8-733d-11e5-9db4-bb5a3652005e.jpg)

**Comment by lirumlarum** [comment]
I had the same issue mentioned above and find out about "npm-check-updates", thats seems to be the most appropriate solution by now.

It lists all outdated packages of the bower file by using following command:
ncu -m bower

all packages can be upgraded by using the --upgradeAll flag (the new dep. version is represented in the bower.json as well)

fyi: by now this thread is pretty good ranked to "bower update save to bower.json" thats why i posted this solution

**Comment by miclaus** [comment]
this is some time ago, however @sheerun it's not really just `rm -rf bower_components && bower install` since one might have the libraries installed to a common directory as defined in `.bowerrc`.
plus i might have other "non-bower" libraries saved to the same directory .

+1  i'd be a useful feature

**Comment by sheerun** [comment]
Hey. I see this feature could be useful, but we need detailed specification how it would work.

If someone would really like this feature in bower, please open new issues with information:

1. How `bower update` and `bower update package` currently works
2. How `bower update --save` and `bower update package --save` should work.

Please also take into consideration:

1. Packages that are not in `bower.json`, but are present in `bower_components` (so called extraneous package)
2. What should be the behavior for dependencies of `package` and dependencies of `package` shared with other packages.

After we have clear specification, we can try find for someone who wants to implement this feature.

**Comment by contolini** [comment]
To clarify some points in this issue:

If you want to update all bower deps to their *latest possible version* and save those changes to bower.json, use [npm-check-updates](https://www.npmjs.com/package/npm-check-updates) (`ncu -um bower`). npm-check-updates is designed to "upgrade your dependencies to the latest versions, regardless of existing version constraints".

`bower update`, on the other hand, is much gentler and respects version constraints in bower.json. This is intentional. Semver is designed to reduce the likelihood of dependencies introducing regressions into your project so it's important that the `update` command follows your version ranges. Bower defaults to the ~ range specifier but you are free to use looser specifiers (^, *, >, etc.) and `bower update` will interpret them appropriately.

So if your bower.json looks like:

```js
"dependencies": {
  "bootstrap": "~2.2.0"
}
```

`ncu -um bower` will change it to:

```js
"dependencies": {
  "bootstrap": "~3.3.6"
}
```

while `bower update --save` will change it to:

```js
"dependencies": {
  "bootstrap": "~2.2.2"
}
```

**Comment by sheerun** [comment]
I think the issue may be it doesn't preseve `^` when saving?

**Comment by sheerun** [comment]
@contolini Could you add another test to ensure it happens?

**Comment by contolini** [comment]
@sheerun True, it doesn't preserve your range specifier. But [neither does `install`](https://github.com/bower/bower/blob/aafe02f3e9682e958d912f74f501f90470e2f984/lib/core/Manager.js#L594). Given:

```
"dependencies": {
  "bootstrap": "^2.2.0"
}
```

Running `npm install bootstrap --save` (the "bower" way to update a dep to the latest possible version) results in:

```
"dependencies": {
  "bootstrap": "~3.3.6"
}
```

I would expect the two commands (install and update) to act the same way so if we change `update`'s behavior, we should also change `install`'s. I'll open an issue about this.

**Comment by sheerun** [comment]
`install` can override dependency, `update `just updates it :) I'd open such issue

**Comment by contolini** [comment]
@sheerun Makes sense. I posed the question over at #2065 to get some feedback before implementing anything.
