### ISSUE TITLE
Awkwardness with components that don't have built versions in repo

### ISSUE THREAD

**Issue by markmarkoh** [bower/bower#150]
I tried using zepto installed through bower and had a strange experience, everything else installed and worked great right out of the box (d3, backbone/_). 

Here was my process, problems I found and the fix:
1. `bower install zepto`
2. realize zepto doesn't include a built version of the library in the repo
3. `cd` to zepto in `components`, run `rake`
4. now everything works locally
5. CI tests fail (and deployment fails)
6. realize zepto includes it's own .gitignore which was ignoring "dist" from my app's repo
7. edit .gitignore and recommit/redeploy 

Am I missing something here? or is the zepto repo in a not-so-bower-friendly state?

edit: This might be something I should take up with the fine folks behind zepto, I just imagine this would be a problem for any library repo that requires a make/npm install/rake build process before it's use.

**Comment by evanshortiss** [comment]
Previously I followed the pattern of including a _dist_ folder for my project that contains the built JS/CSS, but when I heard Bower now allowed use of hooks I thought "great!". After reading about the scripts though I was disappointed to see they only run in a parent project meaning I still need to check in built files which is disappointing. Supporting an npm style _publish_ rather than _register_ would be great, or simply support the _postinstall_ hooks being run for the installed repo. In my case this would be as simple as _npm install && npm run-script bundle_.

What is the plan of action here? Using a separate repo and/or using a dist folder in the original repo both seem like awkward solutions as does expecting the end user to add a post install script if I choose not to go with the previous two options.

**Comment by sheerun** [comment]
@evanshortiss Woulnd't adding such hooks would be a security issue? I agree bower should standardize build configuration, but I'm not sure they should be run automatically. Probably bower could add a field to bower.json that points to pre-built release that could be automatically downloaded instead of source release. Something like:

```
{
  "releases": [{
    "url": "https://uploads.github.com/repos/foo/bar/releases/:version/assets/component.tar.gz",
    "build": "npm install && gulp build"
  }]
}
```

The only question is how to achieve backward compatibility when people stop adding `dist` folders to repositories?
