### ISSUE TITLE
Allow for specification of default dependency range on --save ?

### ISSUE THREAD

**Issue by durp** [bower/bower#1562]
NPM has moved to '^' as default dependency range specifier but allows '~' if you set it in the config. Didn't see any hook in bower to allow for setting the prefix; are plans to continue with the tilde-as-default?

**Comment by Evolter** [comment]
Hello, can we have any feedback on this one, please? Is a behaviour of tilde in dependencies going to be changed? For now it seems that tilde dependencies works bit weird:
```
// packageC
"dependencies": {
  "packageA": "repo-a.git#~1.8.0"
  "packageB": "repo-b.git"
}

// packageB
"dependencies": {
  "packageA": ">=1.6"
}
```
In this case `packageB` will try to fetch `packageA` from github, and we end up fetching `packageA` twice (second one is from specified `repo-a`. Is it a bug or expected?

PS If we remove tilde `repo-a.git#1.8.0` then it will install only one, from `repo-a`.

**Comment by sheerun** [comment]
@Evolter It depends if in registry `packageA` from `packageB` points to the same source as `packageA` from `packageC`. If the source is the same it shouldn't happen (or at least the second time package should be cached).

On the other hand it's not connected with `^` vs `~`. Because you specify version directly in `packageC` bower doesn't even bother to resolve `packageA` any further.

**Comment by Evolter** [comment]
Thanks for the answer.

`packageB` doesn't have source set explicitly, just version (so it uses GitHub). `packageC` points to same repo but hosted elsewhere (so different source). I assumed that if name of package is the same, and source has corresponding version, it shouldn't try to download it again, but it does (but only if in `packageC` we use `~` - without it, it will download only once.

FYI In my case A and B are respectively jQuery and jQuery-UI repos, while C is my private one. The reason of defining different source is because of recent DDoS attack on GitHub. I'm aware that it may be a bit different usage case that Bower should be used for, but I found it misleading that `~` does the difference in this case. I read that in next version there may be "ignore dependencies" feature, which I assume could fix this issue for me, but could you share your opinion about this case?

**Comment by sheerun** [comment]
"Ignore dependencies" would only ignore names, not sources, so I guess your problem will persist.

You'd probably need some kind of dependency-override feature.

**Comment by sheerun** [comment]
Bower is deprecated now, and in maintenance mode. Because of this we won't implement new features like this one. We recommend switching to Yarn or npm, and migrating with [bower-away](https://github.com/sheerun/bower-away)
