### ISSUE TITLE
If private is set to true, then avoid requiring name property

### ISSUE THREAD

**Issue by farinspace** [bower/bower#1571]
If `private` is set to true, then avoid requiring `name`.

I found this feature to be nifty when using npm, since I am just using npm for grunt I can easily create a simple package.json and npm won't bother me with warnings.

```
{
  "private": true,
  "devDependencies": {
    "grunt": "^0.4.5",
    ...
  }
}
```

It would be nice to have bower do the same:

```
{
  "private": true,
  "devDependencies": {
    "bootstrap": "~3.2.0",
    "font-awesome": "~4.2.0",
    "jquery-autosize": "~1.18.12",
    "jcarousel": "~0.3.1",
    "response.js": "https://github.com/ryanve/response.js.git",
    "jquery-throttle-debounce": "https://github.com/cowboy/jquery-throttle-debounce.git",
    "modernizr": "~2.8.3"
  }
}
```

**Comment by superlukas** [comment]
:+1:

**Comment by vsn4ik** [comment]
:+1: for add `private` option.

**Comment by jamesxv7** [comment]
In my opinion the benefit of the error notification offered by the name property is positive since it encourage me to organize my projects (even the private ones). I appreciate having the option that not having at all. I would like to hear more opinions from the community and @bower/contributors.

@sheerun: Any plans to remove name property from private packages?

**Comment by sheerun** [comment]
I think it's safer to not remove it. `name` in package.json makes package name independent from its location on disk (or remote location). It is useful also for private packages.

Without `name` we'd need to default package name to directory name it is in, but it is rather more error-prone because renaming a directory also changes installation directory..

Sorry, for now it won't happen. I see `npm` requires it as well, even for private packages.
