### ISSUE TITLE
bower fails on github call behind internet proxy

### ISSUE THREAD

**Issue by ktodyruik** [bower/bower#1574]
Sorry if this has been posted before. I just can't find a solution to my particular issue. I'm getting an error when running bower within my company's internal network. I'm running bower in Windows 7 and 8. I experience exactly the same issue discussed here, but the solutions are not working for me:
http://stackoverflow.com/questions/21789683/howto-fix-bower-ecmderr

So here is what I get:
```
C:\Projects\temp>bower install jquery
bower jquery#*              not-cached git://github.com/jquery/jquery.git#*
bower jquery#*                 resolve git://github.com/jquery/jquery.git#*
bower jquery#*                 ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/jquery/jquery.git", exit code of #128

Additional error details:
fatal: unable to connect to github.com:
github.com[0: 192.30.252.129]: errno=No error
```

Here is the verbose output:
```
C:\Projects\temp>bower -V install jquery
bower jquery#*              not-cached git://github.com/jquery/jquery.git#*
bower jquery#*                 resolve git://github.com/jquery/jquery.git#*
bower jquery#*                 ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/jquery/jquery.git", exit code of #128

Additional error details:
fatal: unable to connect to github.com:
github.com[0: 192.30.252.130]: errno=No error

Stack trace:
Error: Failed to execute "git ls-remote --tags --heads git://github.com/jquery/jquery.git", exit code of #128
    at createError (C:\Users\ktodyruik\AppData\Roaming\npm\node_modules\bower\lib\util\createError.js:4:15)
    at ChildProcess.<anonymous> (C:\Users\ktodyruik\AppData\Roaming\npm\node_modules\bower\lib\util\cmd.js:102:21)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:755:16)
    at Process.ChildProcess._handle.onexit (child_process.js:822:5)
From previous event:
    at executeCmd (C:\Users\ktodyruik\AppData\Roaming\npm\node_modules\bower\lib\util\cmd.js:61:22)
    at PThrottler._processEntry (C:\Users\ktodyruik\AppData\Roaming\npm\node_modules\bower\node_modules\p-throttler\index.js:89:25)
    at Promise.apply (C:\Users\ktodyruik\AppData\Roaming\npm\node_modules\bower\node_modules\p-throttler\node_modules\q\q.js:1122:26)
    at Promise.promise.promiseDispatch (C:\Users\ktodyruik\AppData\Roaming\npm\node_modules\bower\node_modules\p-throttler\node_modules\q\q.js:752:41)
    at C:\Users\ktodyruik\AppData\Roaming\npm\node_modules\bower\node_modules\p-throttler\node_modules\q\q.js:1337:14
    at flush (C:\Users\ktodyruik\AppData\Roaming\npm\node_modules\bower\node_modules\p-throttler\node_modules\q\q.js:108:17)

Console trace:
Trace
    at StandardRenderer.error (C:\Users\ktodyruik\AppData\Roaming\npm\node_modules\bower\lib\renderers\StandardRenderer.js:82:17)
    at Logger.<anonymous> (C:\Users\ktodyruik\AppData\Roaming\npm\node_modules\bower\bin\bower:110:22)
    at Logger.emit (events.js:95:17)
    at Logger.emit (C:\Users\ktodyruik\AppData\Roaming\npm\node_modules\bower\node_modules\bower-logger\lib\Logger.js:29:39)
    at C:\Users\ktodyruik\AppData\Roaming\npm\node_modules\bower\lib\commands\index.js:40:20
    at _rejected (C:\Users\ktodyruik\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:797:24)
    at C:\Users\ktodyruik\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:823:30
    at Promise.when (C:\Users\ktodyruik\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:1035:31)
    at Promise.promise.promiseDispatch (C:\Users\ktodyruik\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:741:41)
    at C:\Users\ktodyruik\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:557:44

System info:
Bower version: 1.3.12
Node version: 0.10.29
OS: Windows_NT 6.1.7601 ia32
```

I tried
```
git config --global url."https://".insteadOf git://
```
and this had no affect.

Strangely if I run the git command that failed in bower, myself in the console, it works! There is no error.
```
git ls-remote --tags --heads git://github.com/jquery/jquery.git
```

I'm wondering why does this fail when run from bower? I'm confused. I'd love to get bower working at my office. 

Thanks. Any help would be very much appreciated.

**Comment by pdudkiewicz** [comment]
I had similar issue. Git worked, npm worked, bower didn't. Copying .gitconfig directly to my user home directory helped (c:\Users\youruser). I guess bower doesn't check/overwrites HOME environment variable.

**Comment by antigremlin** [comment]
Actually the git URL rewriting option worked for me, but a command is a bit different than posted above:

    C:\dev> git config --global url.https://github.com/.insteadOf git://github.com/

Given you also have ``http_proxy``, ``https_proxy`` and ``no_proxy`` variables set bower starts working. Especially ``bower list`` which is insisting on using git:// URLs to check for updates.

**Comment by kevinSuttle** [comment]
Whoa. Interesting. Thanks @antigremlin @pdudkiewicz for sharing.

**Comment by ChinmayDhavale** [comment]
I am having the same issue. Even after writing the command 
git config --global url.https://github.com/.insteadOf git://github.com/ OR
git config --global url."https://".insteadOf git://
I still get the same error. 
Any suggestions on how to get rid of this error

**Comment by antigremlin** [comment]
@ChinmayDhavale could you try executing the failing git command manually and post the results here? Please also post your environment variables (http_proxy, https_proxy, no_proxy).

**Comment by KostyaSha** [comment]
I feel like bowler is broken somewhere (cache management maybe), but i have no details atm.

**Comment by hranicka** [comment]
I also sometimes get `Failed to execute "git ls-remote --tags --heads git://github.com/twitter/typeahead.js.git", exit code of #128 fatal: unable to connect to github.com: github.com[0: 192.30.252.129]: errno=No error"`

Composer or raw git cloning works fine. It seems only bower is broken :(

**Comment by BrianAdams** [comment]
I believe the errors with the #128 is due to the git client making a call to the "dumb" http api that was long ago depreciated: 

in the example below it is calling: https://github.com/mouse0270/bootstrap-growl.git/info/refs when executing git through bower.  No problem when executed through the commandline.


When executed via bower
>bower install openrov-dive-alerts
[?] May bower anonymously report usage statistics to improve the tool over time? Yes
bower                        ENOTFOUND Package openrov-dive-alerts not found
rov@OpenROV:/tmp$ /opt/openrov/cockpit/node_modules/bower/bin/bower install openrov-plugin-divealerts
bower openrov-plugin-divealerts#*       not-cached https://github.com/BrianAdams/openrov-plugin-divealerts.git#*
bower openrov-plugin-divealerts#*          resolve https://github.com/BrianAdams/openrov-plugin-divealerts.git#*
bower openrov-plugin-divealerts#*         download https://github.com/BrianAdams/openrov-plugin-divealerts/archive/v0.0.3.tar.gz
bower openrov-plugin-divealerts#*          extract archive.tar.gz
bower openrov-plugin-divealerts#*         mismatch Version declared in the json (0.0.0) is different than the resolved one (0.0.3)
bower openrov-plugin-divealerts#*     invalid-meta openrov-plugin-divealerts is missing "ignore" entry in bower.json
bower openrov-plugin-divealerts#*         resolved https://github.com/BrianAdams/openrov-plugin-divealerts.git#0.0.3
bower bootstrap.growl#~2.0.0            not-cached https://github.com/mouse0270/bootstrap-growl.git#~2.0.0
bower bootstrap.growl#~2.0.0               resolve https://github.com/mouse0270/bootstrap-growl.git#~2.0.0
bower bootstrap.growl#~2.0.0               ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/mouse0270/bootstrap-growl.git", exit code of #128
>
>Additional error details:
error: The requested URL returned error: 403 while accessing https://github.com/mouse0270/bootstrap-growl.git/info/refs
fatal: HTTP request failed

From the command-line:
>rov@OpenROV:/tmp$ git ls-remote --tags --heads https://github.com/mouse0270/bootstrap-growl.git
74ecdbc6410deaa4d7be9b6ce9c32e67ad35ca8c	refs/heads/beta-3.0.0
1257c94ee50c7d284b880c826a2da18bd4cb57ca	refs/heads/master
dafb2377b1b022d6d599208a32c29fba8e70fb6e	refs/heads/meteor-testing
45b10189d5598ddc208a0a40674efbe3b2ca2f0c	refs/heads/old-2.0.1
9d0d8fead35f80fa8ccce5c8f4b25bc24408f7dd	refs/tags/1.0.6
25cb292632d8e9a0581273ee090ddbd65f161848	refs/tags/2.0.0
73d2fc9b86d7a011be4a304f80d14a3ee5310bcb	refs/tags/2.0.0^{}
45b10189d5598ddc208a0a40674efbe3b2ca2f0c	refs/tags/2.0.1
0301fc9b6a6ec8f5fa2b61feefe53ec6046d5a5c	refs/tags/3.0.0
74ecdbc6410deaa4d7be9b6ce9c32e67ad35ca8c	refs/tags/3.0.0b
889a91ea1fc6bfa05b434a259cd625a7664f9d3c	refs/tags/3.0.1
b3b8e22f3995dc5521a79846211da265fab1d947	refs/tags/3.0.2

**Comment by MisterFantastic** [comment]
Try this one. It seems to be working for me in corporate proxy.
git config --global http.sslverify false

**Comment by pkosenko** [comment]
If you are running a bower.json file, try adding the following to the ".bowerrc" config file to use  custom paths rather then the bower default of "git://".  

"shorthand-resolver": "https://github.com/{{package}}/{{package}}.git"

**Comment by sheerun** [comment]
It will be fixed in next version of bower via passing HTTPS_PROXY and HTTP_PROXY variables in environment variables: https://github.com/bower/config/commit/5343803017c81034011c7098466187dfab4ec199

**Comment by pkosenko** [comment]
Sounds good.  Thanks for the reference.

**Comment by kunalgithub** [comment]
This does not work (1) Tried port 22 (2) instead of (3) proxy settings  - Any Resolutions

**Comment by keeprock** [comment]
@antigremlin your rewriting options works for me! Thanks!

**Comment by nathanhleung** [comment]
@antigremlin worked for me too, :+1:

**Comment by sheerun** [comment]
Glad it works for you. I'm locking to prevent more :+1: to prevent noise in issue tracker.
