### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by ilanbiala** [bower/bower#1622]
[Some of them](https://david-dm.org/bower/bower#info=dependencies&view=table) are really out of date.

**Comment by laurelnaiad** [comment]
Thank you for linking the chart, @ilanbiala .

Due to the age of `request`, and in particular the age of its `hawk` dependency, it seems, we also see a bunch of warnings on npm install which are distracting and unsettling. When I see components demanding node 0.8.x, I really wonder whether the staleness is going to lead to issues...

So :+1: . Any particular reason *not* to keep the dependencies relatively up to date?

**Comment by ilanbiala** [comment]
@laurelnaiad yep the warnings are distracting and confusing for new users, plus Bower would probably be faster and more secure (security and error-wise) with the updates.
