### ISSUE TITLE
bower install --save --save-exact

### ISSUE THREAD

**Issue by rightaway** [bower/bower#1636]
Like `npm install` offers a `--save-exact` flag (see https://github.com/npm/npm/issues/2911), it would be great it `bower install` would offer the same so that installing a particular package would install that exact version to bower.json like `1.2.3` instead of `~1.2.3`.

**Comment by sindresorhus** [comment]
:+1: PR welcome.

**Comment by pulkitsinghal** [comment]
I ended up here looking for a solution where if I specify ` bower install --save --save-exact angular-resource#^1.3` and select option `1) angular#1.3.16 which resolved to 1.3.16 and is required by ...` then in `bower.json` I was hoping it would save `1.3.16` as the version but that's not the case, it saves `^1.3`

I understand that the motivation and solution for this issue was much simpler but I'm also curious about how to accomplish what I've described. Thoughts?

**Comment by sheerun** [comment]
It has been already released
