### ISSUE TITLE
Error in extracing/parsing/resolving packages

### ISSUE THREAD

**Issue by pertyjons** [bower/bower#1709]
I have struggling with a strange error last couple of days and I have no real clue of what the actual error could be. I only get this error when I run on a buildagent/user on teamcity 8.1.5 which is a linux box.

I think the error occurs when the archive is extracted or after. When I look at the cache for example the bower-angular-animate it looks like this:

```
[x@y packages]$ ls -al 356e4c998521bf70df724ec1b81b9258/1.3.13/
total 6
drwxrwxr-x. 2 builduser13 builduser13   8 Feb  9 12:06 bower-angular-animate-1.3.13
-rw-rw-r--+ 1 builduser13 builduser13 362 Feb 23 13:37 .bower.json
```

When looking at a working package it looks like this (in this case bower-angular-scenario):

```
[x@y packages]$ ls -al 40860fd5b0240909ec973fa4a8aed8c3/1.3.13/
total 1301
-rw-rw-r--+ 1 builduser13 builduser13 1267886 Feb  9 12:06 angular-scenario.js
-rw-rw-r--+ 1 builduser13 builduser13     465 Feb 23 13:37 .bower.json
-rw-rw-r--+ 1 builduser13 builduser13     156 Feb  9 12:06 bower.json
-rw-rw-r--+ 1 builduser13 builduser13     120 Feb  9 12:06 jstd-scenario-adapter-config.js
-rw-rw-r--+ 1 builduser13 builduser13    5784 Feb  9 12:06 jstd-scenario-adapter.js
-rw-rw-r--+ 1 builduser13 builduser13     621 Feb  9 12:06 package.json
-rw-rw-r--+ 1 builduser13 builduser13    2178 Feb  9 12:06 README.md
```

In the first case above the .bower.json file is missing the ignore and main keys:

```
[13:37:23]bower angular-animate#1.3.13            invalid-meta angular-animate is missing "main" entry in bower.json
[13:37:23]bower angular-animate#1.3.13            invalid-meta angular-animate is missing "ignore" entry in bower.json
```

So there seems to be some problem when either moving/extracting or resolving the package as the directory is the full package name. In the latter case it's only the version 1.3.13 which are the directory and also the .bower.json is located inside the version directory and contains the right keys for ignore and main.

I have created a rather lengthy question on Stack Overflow with some more information.

http://stackoverflow.com/questions/28545106/bower-installs-same-package-different-in-file-structure

I understand there could be some configuration in my buildserver which is causing this but as it also looks like a bug. 

Any feedback or pointers in any directions are more than welcome.

(I'm sure the timestamp of the file has nothing to do with it as I can reproduce it ;-)

**Comment by grebett** [comment]
Using Cygwin in Windows 8.1, i got this issue trying `npm install bower` : 

<pre>
npm ERR! Failed to parse json
npm ERR! Unexpected token �
npm ERR! File: C:\Users\Sly\AppData\Roaming\npm-cache\intersect\0.0.3\package\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "instal "bower"
npm ERR! cwd C:\cygwin64\home\Sly\jktv\videocity\basis
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! file C:\Users\Sly\AppData\Roaming\npm-cache\intersect\0.0.3\package\package.json
npm ERR! code EJSONPARSE
npm ERR! not ok code 0
</pre>

Install is not working since parsing is failing. May be related to your error, isn't it ?

**Comment by pertyjons** [comment]
Nope, don't think so. You have a problem with an npm package and my problem is related to packages of bower behaving strange. You problem looks like there are a bad package.json file in the intersect package.

**Comment by pertyjons** [comment]
Hmmm... Looking through some of the other tickets and I wonder if the problem could be that boer is using the "process.env.home" as described in #1631 and #1715 issue.

**Comment by sheerun** [comment]
This issue got stale. If this is still relevant, please create another one
