### ISSUE TITLE
QUESTION: How To delete; /root/.cache & /root.config/configstore & /root/.local/bower?

### ISSUE THREAD

**Issue by ghost** [bower/bower#1750]
Hi,

I'm building Popcorn-Time with these cmds;

```
npm config set cache $TMP/npm-cache
npm install grunt-cli bower
npm install
bower install --allow-root
grunt build
bower cache clean --allow-root
npm config delete cache
```

When it's done building I have these /paths created;

```
 /root/.cache/bower
(but it creates the ~/.cache and I want to remove cache)

/root.config/configstore 

/root/.local/bower
```

I've been digging around and reading, and the best I can come up with for cleaning up bower is;

`bower cache clean` but this only cleans out `/root.cache/` but it still leaves it behind and all the other directories it creates.

I want be able to delete all the /paths I mentioned above, I assume bower is creating, is there a way to get rid of these?

thank you

**Comment by meuwe** [comment]
Hi,

Any thoughts here please?

thank you

**Comment by akostadinov** [comment]
I don't think cleaning up config makes sense. It should be like `bower uninstall`. But would be a little confusing because it wont actually remove bower itself. Not sure. I filed an issue to make these paths configurable. See #2412.

Probably some command like `bower show assets` or something to list all files owned by bower which user can then delete if desired.

**Comment by ivaaaan** [comment]
Any updates?

**Comment by sheerun** [comment]
This issue got stale. If this is still relevant, please create another one
