### ISSUE TITLE
.config/bower.json

### ISSUE THREAD

**Issue by shannonmoeller** [bower/bower#1794]
As more and more tools have become best-practice when authoring npm modules, from `package.json` to `.*rc` to `*file.js`, the root directory of projects has become a very loud place. This dot-noise pushes README content farther and farther down the main page of git repos.

![screenshot 2015-05-01 21 41 51](https://cloud.githubusercontent.com/assets/155164/7439468/e8f2ff9e-f04a-11e4-8c1b-4248379053e9.png)

What if the above could optionally be simplified to the following?

![screenshot 2015-05-01 21 50 12](https://cloud.githubusercontent.com/assets/155164/7439513/179455c2-f04c-11e4-9577-c3b73c2b01c3.png)

This is a simple example and that's already about a 30% vertical space savings. I started the conversation over in the [npm repo](https://github.com/npm/npm/issues/8159), but I'm also submitting issues to the `findup`, `karma`, `travis-ci` and `zuul` repos.

**Comment by jamesxv7** [comment]
This issue/enhancement is properly discussed in multiple repositories, such [npm]( https://github.com/npm/npm/issues/8159) just to mention one. Due to the impact that can cause this kind of change I'll lock the issued. I understand it is a good initiative and we must ensure that not only the Bower Community is on board but also the different components and players that comprise the front and back end ecosystem.

I agree and somehow I'm aligned with @othiym23 [comments](https://github.com/npm/npm/issues/8159#issuecomment-99691137).

**Comment by sheerun** [comment]
It would be better to incorporate bower.json into package.json instead, but we need to figure out how to maintain backward compatibility first.
