### ISSUE TITLE
feature: proxy exclusion/bypass list

### ISSUE THREAD

**Issue by igorlino** [bower/bower#1803]
Hi,

1st of all, I love using bower, I find it very convenient and robust. Has served me well all these time.

Long story short: there is a cases where the proxy setting plays against using it. Public packages use proxy, private packages behind a strict proxy (under some internal domain) should not use proxy.

Recently I'm doing a project under a string proxy umbrella that requires, well, proxy settings. That works fine.
In a later stage of the project we have had start creating private bower packages (for feeding private-bower), that exist only within the protected network AND THERE is where you want to get some host to be bypassed without proxy settings being use in the HTTP request.

I think these feature could save a lot of pain and enable a quite wide ecosystem of bower used behind corporate proxy for private bower repositories.

The bower config could include something like:

```json
"proxy-bypass-list":["domain1", "domain2"]
```

I think it should be relatively easy to implement.  I can of course provide a PR.

Comments, opinions, suggestions are very welcome.

**Comment by nwinkler** [comment]
I'm in the same situation as you (corporate proxy with NTLM authentication for public packages, private Git server with our own packages, doesn't need to go through the proxy), but I find that things are working well for me with the current implementation.

To use the proxy, I'm setting the following environment variables - since all of our packages (public on GitHub/Bower registry, private on our own Git server) use Git, the standard environment variables used by Git work fine:

* http_proxy/HTTP_PROXY: Define the proxy used for HTTP, e.g. http://our-proxy:8080
* https_proxy/HTTPS_PROXY: Define the proxy used for HTTPS, e.g. http://our-proxy:8080
* ALL_PROXY (not sure if that's needed, but I've added it for good measure): Used by some command line tools, e.g. http://our-proxy:8080
* no_proxy/NO_PROXY: Comma-separated list of proxy exclusions, e.g. "127.0.0.1,localhost,git.corp.com"

The `NO_PROXY` environment variable should allow you to exclude certain hosts/domains from using the proxy, and Git/Bower should use that. Like I said, for me this is working fine.

Can you describe your setup (especially how you configure your proxy settings) in more detail?

**Comment by igorlino** [comment]
Interesting solution (usage of variables), thanks a lot, did not find it after looking for it. NO_PROXY was the keyword.  

I had also faced problems with npm, but managed to get it working.  It was not only about proxy but credentials.

So this the setup:
* http_proxy/HTTP_PROXY: Define the proxy used for HTTP, e.g. http://our-proxy:8080
* https_proxy/HTTPS_PROXY: Define the proxy used for HTTPS, e.g. http://our-proxy:8080

* The private git repository/server is gitlab with no HTTPS enabled, and single user with multiple accounts. Problem is that bower requires the git protocol to register packages. (GIT:// translates to https). Our gitlab installation does not support HTTPS. Solution: Add git URL transformation rule  http://gitlab instead of Git://gitlab
* The git repository has specific credentials per user.  Problem: credential-helper store or cache. works fine when calling GIT in the console but fails under bower and also is not mmm secure or practical for multiple developers. Solution: using winstore http://gitcredentialstore.codeplex.com/  It stores the user and password securely, bower recognizes it :)

ok, I will try out the NO_PROXY  (env-variable-based  bypass), and report back.

If the NO_PROXY works, I think, it would still be important to have something in bowerrc. I mean you can define a proxy there already, so it would be fair enough to bypass it also there  ;)

**Comment by igorlino** [comment]
A related issue is at https://github.com/bower/bower/issues/857

**Comment by sheerun** [comment]
NO_PROXY handling should be implemented in next version of bower via https://github.com/bower/config/commit/5343803017c81034011c7098466187dfab4ec199
