### ISSUE TITLE
Bower hangs on "bower not-cached bower resolve"

### ISSUE THREAD

**Issue by HassanMehmood92** [bower/bower#1899]
Bower hangs while installing the dependencies 
![image](https://cloud.githubusercontent.com/assets/13550768/9513459/cb4c4480-4ca9-11e5-8164-0c2581d9dd64.png)
my bower.json file looks like this
{
  "name": "challenges_bower",
  "version": "0.0.0",
  "main": "index.html",
  "license": "MIT",
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "test",
    "tests"
  ],
  "dependencies": {
    "restangular": "~1.5.1",
    "ngstorage": "~0.3.7",
    "angular-ui-router": "~0.2.15",
    "angular": "~1.4.2",
    "underscore": "~1.8.3",
    "ng-file-upload": "~5.0.9",
    "nginfinitescroll": "~1.2.1",
    "angular-notify": "~2.5.0",
    "moment": "~2.10.6"
  }
}

Also
Bower update and bower install doesn't create components 
as specified in .bowerrc file

{

	"directory" : "bower_components"

}

**Comment by sheerun** [comment]
Works for me. Could you check if it still doesn't work for you?

**Comment by HassanMehmood92** [comment]
No, It is still not working I have been waiting for more than 3 hours. Are there any kind of flags available like with npm to see where the problem lies? Also is there any global PATH or a directory required for bower itself ?

**Comment by sheerun** [comment]
Maybe you are behind a proxy? Does following work for you?

```
git ls-remote --tags --heads git://github.com/moment/moment.git
```

**Comment by HassanMehmood92** [comment]
![reply](https://cloud.githubusercontent.com/assets/13550768/10130176/6fb61570-65df-11e5-8d5a-05fd5d5ed71b.PNG)

I am getting the following results,  I guess it's not the proxy issue either

**Comment by sheerun** [comment]
I have no idea what is going on, sorry

**Comment by orcwarrior** [comment]
I've got same problem after node and npm update, installing older bower version (1.3.0) resolves problem for me.

**Comment by NiteshOswal** [comment]
Maybe you can try using `bower install --verbose` OR `bower update --verbose` to see what's going on under the hood?

**Comment by MisterFabulous** [comment]
I had the same problem. Here in Oman, where I am currently working, they seem to block some things which bower try to resolve. After connecting to a VPN outside Oman it worked. It would be good if bower would not hang forever in this case, but give useful errors, if possible.

**Comment by HassanMehmood92** [comment]
Same Issue --verbose flag doesn't do anything
![image](https://cloud.githubusercontent.com/assets/13550768/12258873/b8a51306-b933-11e5-8a08-bbe6e51cb54d.png)

**Comment by kbanashek** [comment]
Did you ever resolve this issue?

**Comment by kukiel** [comment]
The same issue.

bower 1.7.9
git 2.8.3.windows.1
npm 3.3.9
node 4.4.5

cannot install any package in any project, it prints resolve/not-cached for every package and hangs..

any ideas?

**Comment by kukiel** [comment]
I stopped using bower - that helped :)

**Comment by DJDaveMark** [comment]
I had the same problem & solved it with `bower cache clean` (after the underlying problem was fixed)

**Explanation**
On our CI platform one of our other projects (built every night) failed with the following error (which references a private in-house project hosted on a private internal GitLab):
`bower private-project#2.3.*                                  ECMDERR Failed to execute "git ls-remote --tags --heads http://gitlab.example.com/example/private-project.git", exit code of #128 fatal: unable to access 'http://gitlab.example.com/example/private-project.git/': The requested URL returned error: 504`

Later on in the day I decided to clean up / reinstall all dependencies on a new project I was working on, and bower just hung. Since I had just installed everything (too much) the day before, I knew it wasn't because of any new dependencies.

Thanks to this issue, I did: `git ls-remote --tags --heads http://gitlab.example.com/example/private-project.git` which worked fine.

I then removed `private-project` from `bower.json` and everything else installed correctly (bower didn't hang). I added the `private-project` back in and bower hung again.

After `bower cache clean` everything installed correctly again.
