### ISSUE TITLE
Possibly unreasonable defaults with bower install with no args

### ISSUE THREAD

**Issue by MichaelXavier** [bower/bower#1908]
There may very well be a good reason for this behavior so if there is I'd love to know. Here's an example:
1. bower init a new project.
2. Add a dependency `"polymer":"=0.5.6"`
3. `bower install`
4. Edit the dependency to `"polymer":"=1.0.0"`
5. `bower isntall`

You get a conflict because it tries to preseve any dependencies you happen to have lying around, even if they are superceded by bower.json, which should be your canonical listing of dependencies for your project. Instead if you do `bower update`, it does what you'd expect which is take your bower.json and try to come up with a build plan for it.

I understand the purpose of `bower install <packagename>` as being a imperative way to install a package, but `bower install` with no args just seems like a strictly worse version of `bower update`. The problem is that most package managers I've used use an `install` subcommand to do an "install and update" like update does, so its going to be the one people reach for, and you can lose a lot of time figuring out why `bower install` is trying to install phantom versions that are not listed in your bower.json. It looks like in recent versions `bower update` even works on a fresh project with no `bower_components`, so my question is why doesn't `bower install` with no arguments just do the same thing as bower update?

**Comment by NobodysNightmare** [comment]
I came here to ask the very same question.

For us it turned out that one of our dependencies had a bug and now we needed version`1.10.6` or later, but in no case an earlier version. So I specified `~1.10.6`, but it refused to install that version and instead kept staying at `1.10.2` for me (which was the version installed until then). I would not have expected that, since `1.10.2` is not "allowed" by our `bower.json`.

Only `bower update` will install the correct vesion for me. So is that intended?
Should I run `bower update` in situations where I would run `npm install` or `bundle install`?

**Comment by sheerun** [comment]
Isn't this because `polymer`'s dependencies produce circular dependency?

Does it happen with other packages as well?

**Comment by MichaelXavier** [comment]
Oh wow gross. I didn't realize that. It looks like only old versions of polymer had a circular dependency. I just tried this with jQuery (installed 1.0.1, then 2.0) and it seemed to work fine. Still, I wonder if there's better feedback to provide or if there's still a bug here. The fact is that the bower.json file only specified the new version of polymer (which has no circular dependency) and it still got trapped in the existing dependency's circular dependency. If not the default, it seems like there should be a mode to bower where the bower.json is the canonical dependency set.
