### ISSUE TITLE
.bowerrc does not support absolute paths

### ISSUE THREAD

**Issue by indolering** [bower/bower#1914]
Bower treats `/Users/indolering/bower-test/parent-element/bower_components` as a relative path and install everything in a sub-directory.

This might seem like a small thing but confusing as hell and makes it difficult to work on multiple assets that have linked dependencies.  Consider the following setup:

```
/home
+--project-directory
   |--.bowerrc
   +--parent-element
      +--bower_components
          *--symlink to child-element directory
   +--child-element
```

Polymer [does some magic](https://github.com/PolymerLabs/polyserve) with paths and will serve the child element out of the `parent-element/bower_components` directory.  Instead of being able to specify a single path in a .bowerrc file pointing to parent-element/bower_components, one must add a .bowerrc to *every* child directory and specify a relative path.

**Comment by sheerun** [comment]
I don't understand. You want to put absolute path as `cwd` property in `.bowerrc` file? 

If yes, using absolute paths makes application tied to one computer, it's not a good practice.

**Comment by indolering** [comment]
No, I want to specify the `directory` (aka `bower_components`).

FWIW, I don't think including a .bowerrc file in a project is a very good idea, considering it can override critical security settings.

**Comment by sheerun** [comment]
What is your .bowerrc in this case?

**Comment by indolering** [comment]
> What is your .bowerrc in this case?

```
{
  "directory": "/path/to/bower_components"
}
```

**Comment by gronke** [comment]
:+1: 

An example why this is useful: Polymer Elements expect to be installed to a flat directory structure as sibling folders to their dependencies. When you put a `.bowerrc` in the top directory that has an absolute path, you can `cd/` to your elements directories and install dev-dependencies, etc.

```
.
├── .bowerrc
├── polymer-dependency
└── polymer-element
```

**Comment by indolering** [comment]
@gronke Yup, I ran into this while setting up development of multiple Polymer elements.  @sheerun, this is a real world problem that more people are going to run into as Polymer usage rises.

**Comment by faceleg** [comment]
> @indolering FWIW, I don't think including a .bowerrc file in a project is a very good idea, considering it can override critical security settings.

You could add the non security related settings into you repository's bowerrc, the rest into your system bowerrc

**Comment by gronke** [comment]
@faceleg How do you differentiate between security related settings? The [script execution hooks](https://github.com/bower/bower/issues/1886) are something you might want to disable entirely. But what about security implications caused by directory traversal? So where's the difference between safe and unsafe options and how do you ensure only the safe ones land im your project's `.bowerrc`?

**Comment by faceleg** [comment]
See my question on #1886 regarding security issues.

**Comment by sheerun** [comment]
@gronke Then shouldn't instead we allow for something like:

```
{
  "directory": "."
}
```

@indolering How you know `/path/to/` exists on other developer computers that checkout your repo? As I said using absolute tries repository to your computer / platform / specific location in system.

**Comment by gronke** [comment]
The relative path from the `directory` option is not resolved relative to the `.bowerrc` file. An absolute path would always resolve to the same directory, even if Bower is executed from a sub-directory.

For developing Polymer Elements you have [a directory structure like commented above](https://github.com/bower/bower/issues/1914#issuecomment-156852033). You want to work on a single element, while having it's dev-dependencies installed to the same directory your Element is stored in itself.

```
$ tree -a
.
├── .bowerrc
├── polymer-dependency
└── polymer-element

$ git clone https://github.com/PolymerElements/iron-ajax
$ cd iron-ajax/
$ bower install --dev
```

#### Actual result with `{ "directory": "." }`
(Dev-)Dependencies are installed to `./iron-ajax/` rather than to `./`

```
$ tree -a
.
├── .bowerrc
├── iron-ajax
│   └── test-fixture
├── polymer-dependency
└── polymer-element
```

#### Aimed result (with an absolute path)
All dependencies, even from sub-directories, will install their dependencies directly to the top directory.

```
$ tree -a
.
├── .bowerrc
├── iron-ajax
├── polymer-dependency
├── polymer-element
└── test-fixture
```

**Comment by indolering** [comment]
@sheerun as @gronke illustrated, this directory structure is a requirement for development.

I don't understand the resistance to feature, the current behavior simply does not comply with standard path syntax.  It would be one thing if I was advocating a change that went against convention but the only downside to supporting this is that some users *with incorrect configs* may experience issues when upgrading.  If that's a concern, then I would support opt-in behavior ("use absolute" maybe?) and a warning for a few versions....

**Comment by gronke** [comment]
Good point @indolering! What if people have  already configured their directory to `/bower_components/` instead of `bower_components/`? They would end up installing  their dependencies to a subdirectory of `/`.

IMO cli flags for every new feature are not the best solution. On the other hand we can [protect the users from affecting files or directories outside of `process.pwd()`](https://github.com/bower/bower/issues/1891) (closed). When you run `bower install` in `/var/www/` and it would create files in `/bower_components` an error should occur that can be suppressed by adding `--no-sandbox` (or something like that).

@sheerun Why should we actively prevent users from tying their configuration to one machine? Not every package is for public release.

**Comment by sheerun** [comment]
I need to evaluate security of such feature

**Comment by gronke** [comment]
Thanks. Let me know if I can help with that!

**Comment by sheerun** [comment]
For example what happens if someone sets `directory` to `/etc` or some other secure directory..

What directories should we permit and what should we not.

**Comment by gronke** [comment]
We can resolve the path and check if it's a real sub-directory of `process.cwd()`. If it's not, it's likely to be an attack and we should throw an error. 

Users who really need to traverse directories could either 
- set a cli flag to bypass this check entirely
- provide a list of allowed paths analog to [PHP's (deprecated) open_basedir](http://php.net/manual/en/features.safe-mode.php#ini.open-basedir)

I'd prefer the second option, because there's no need to disable the security check entirely.

**Comment by indolering** [comment]
> For example what happens if someone sets directory to /etc or some other secure directory...

At least for OS X, installing things into `/etc` requires sudo.

Furthermore, Bower doesn't check relative links to ensure that they are pointing to subdirectories.  I was able to get Bower to install JQuery in `/etc/hellobower/` by overloading the number of relative parent links (which is clipped to the root directory): `../../../../../etc/hellobower`

> What directories should we permit and what should we not.

I also searched through the first 1K `.bowerrc` files on Github and only three of them had absolute paths, all pointing to root.  I think just blacklisting root and common top level directories would be good enough.  If you want to get elaborate, you could check if the target directory is empty or has child directories that contain `bower.json` files.  

> We can resolve the path and check if it's a real sub-directory of process.cwd().

Since Bower checks the parent directory for `.bowerrc` files, you would have to check if it's a subdirectory of the `.bowerrc` file where the setting is declared.  I feel as if people should be able to opt-out of such protections ... but I'm having a hard time articulating a use-case to justify an exception.

> I need to evaluate security of such feature.

I don't agree that this is a security issue, Bower is ostensibly for managing code that runs in the browser, but that's not always the case.  You could craft an evil package that runs "unit tests" in Node, for example.

I do agree that the change makes it easier for users to shoot themselves in the foot.  For those with misconfigured directory settings, display a warning and offer to convert absolute paths to relative paths for a few months.  After that, blacklisting common system directories, scoping to subdirectories of the `.bowerrc` file, and perhaps a sanity check based on the contents of the target directory should be good enough.

**Comment by sheerun** [comment]
Ok, I'm convinced. It won't more less secure than `directory` is now. I'll accept a PR with tests.

**Comment by indolering** [comment]
@sheerun Where is the relevant code and what "don't shoot yourself in the foot" protections are you expecting?  Not sure if I will have the time to contribute here : (

**Comment by sheerun** [comment]
Unfortunately it's probably in multiple places in code. Or maybe bower/config reads it incorrectly.

**Comment by indolering** [comment]
Ugh, [the code][1] just concatenates the `directory` path with the **process'** `cwd`, which fucks with the directory setting of any `.bowerrc` file residing in a parent directory:

```
/home
+--parent
   |--.bowerrc // "directory": "a/bower_components"
   +--a
   +--b
      +--a
         +--bower_components
```

The amount of due-diligence required to prevent data loss isn't worth the effort and I actually think the current behavior is a bit more newb friendly.  Why don't we instead use a new syntax for opting into the technically correct path finding behavior?

``` Javascript
"directory" : {
    "path" : "supports absolute paths and resolves relative paths based on .bowerrc directory"
    "unsafe" : false //disables directory blacklist and/or checking if path is child of .bowerrc file
}
```

This could be handled by a simple `if (typeof path === "object")` statement.  


[1]: https://github.com/bower/bower/search?utf8=%E2%9C%93&q=%22path.join%28this._config.cwd%2C+this._config.directory%29%22&type=Code

**Comment by gronke** [comment]
@indolering I like the idea to switch to the new behavior with the transition to [allow the directory to be specified from bower.json](https://github.com/bower/bower/issues/1986) Path resolution could be part of https://github.com/bower/json, so that this repo would only have to be touched for removing the join with `process.cwd()`.

In case we want to adapt the changes in Bower directly, the tests for directory resolution would clutter through https://github.com/bower/bower/tree/master/test/commands, what could make it a little more difficult to understand the behavior from reading the tests.

We should pay some attention to the [ignore pattern](https://github.com/bower/bower/blob/master/lib/commands/init.js#L277) that could be affected by the change.

:heart_decoration: `unsafe` option btw.

**Comment by indolering** [comment]
@gronke That would be cleaner and I would actually drop the "unsafe" option.  It's basically there to justify the new syntax.

But does `bower.json` respect any `bower.json`'s found in parent directories?

**Comment by gronke** [comment]
The `unsafe` option is actually a simple way to prevent directory traversal attacks #1890 and could be foreseen today and easily shipped in a second PR.

@indolering could you live with passing the absolute directory path via `--directory` flag? For Polymer Element development that would perfectly work for me at least.

**Comment by sheerun** [comment]
- We can't change format of `directory` for backward compatibility.
- We can't change the behavior of `directory` for the same reason 
- `bower.json` is not merged in any way with parent `bower.json`

**Comment by sheerun** [comment]
I can only accept PR that allows for absolute path in `directory` field because this behavior is currently undefined.

**Comment by gronke** [comment]
gotcha @sheerun !  To not expand this discussion to, I'll create a PR for this, so that we have some code to discuss upon. Would you like to assign this one to me?

**Comment by indolering** [comment]
> @indolering could you live with passing the absolute directory path via --directory flag? For Polymer Element development that would perfectly work for me at least.

But wouldn't that require me to drop that into every Bower command?  It would be easier to just use my parent directory hack than type `bower install jquery --save --directory /path/to/bower_components`.

> bower.json is not merged in any way with parent bower.json

Which basically kills our primary use case.  This setting is only useful as a way of consolidating Bower assets across multiple projects.

> We can't change format of directory for backward compatibility.

But the change I'm proposing would only break older versions of Bower that haven't been updated and ONLY if you happen to have this specific `directory` config.  

> We can't change the behavior of directory for the same reason ... I can only accept PR that allows for absolute path in directory field because this behavior is currently undefined.

Just because it's "undefined" doesn't mean that a change wouldn't break backwards compatibility.  Changing the existing behavior would require a lot more work because it would require warnings, automatic conversions, etc.  Changing the syntax would break backwards compatibility but wouldn't run the risk of data loss and thus wouldn't require warnings.

We could just add a new directive, such `path` or `bower_components`.  This would be more elegant in the long run and allow us to phase out the older incorrect behavior entirely.

**Comment by sheerun** [comment]
> But the change I'm proposing would only break older versions of Bower that haven't been updated and ONLY if you happen to have this specific directory config.

I'm not willing to change this field from string type to object type

> This would be more elegant in the long run and allow us to phase out the older incorrect behavior entirely.

I still think that using absolute paths in configuration is non-portable. The current behavior of relative paths is for me more sensitive. I woudn't call it "incorrect behavior".

I can still accept a PR with tests that allows for absolute path in `directory` field in `.bowerrc`.

@gronke Feel free to assign this task on you. I've added you to bower organization.

**Comment by indolering** [comment]
> I'm not willing to change this field from string type to object type

It would only be an object type for absolute paths, any `"directory" : "path"` entries would continue to be resolved using the current logic.

**Comment by indolering** [comment]
But, of course, for external projects my solution would complicate simply reading the path.

**Comment by indolering** [comment]
+1 @gronke!

**Comment by gronke** [comment]
@indolering :beers:
