### ISSUE TITLE
shorthand_resolver and `bower list`

### ISSUE THREAD

**Issue by jaworskm** [bower/bower#1933]
We have a corporate, internal git repository. I used shorthand_resolver in the `.bowerrc` file like

```
{
  "shorthand_resolver": "https://repo.company.com/scm/{{owner}}/{{package}}.git{{version}}"
}
```

the bower.json file requires repositories as below where the library is at `https://repo.company.com/scm/mylib/ui-core-brand.git1.1.0`:

```
{
  "dependencies": {   
    "ui-core-brand": "mylib/ui-core-brand#1.1.0"
  }
}
```

When I type `bower install` everything is great. If I type `bower list` it fails with:

```
bower ECMDERR       Failed to execute "git ls-remote --tags --heads mylib/ui-core-brand.git", exit code of #128 fatal: 'eabui/ui-core-brand.git' does not appear to be a git repository fatal: Could not read from remote repository.  Please make sure you have the correct access rights and the repository exists.
```

If I type `git ls-remote --tags --heads https://repo.advisory.com/scm/mylib/ui-core-brand.git` the git command works as expected. Am I doing something wrong? Or does the shorthand_resolver not apply to `bower list`?

Thank you.

**Comment by Polooo2** [comment]
I am having a similar issue. 
At my company we are using shorthand resolvers for our internal repositories. Now we included an external lib (angular-gridster) which has a dependency on "sdecima/javascript-detect-element-resize#~0.5.1"

Bower install works without problems. BUT as soon as I try to use bower list I am getting an error because bower is trying to resolve the dependency of angular gridster with the shorthand resolver of my root project and not the default one (github).

I think the shorthand resolver of the root project shouldnt be applied to dependencies?

**Comment by lfaveur** [comment]
anyone solved it ? :/

**Comment by jaworskm** [comment]
We had the same issue at our company because we wanted to use Polymer and our internal collection of components. I wrote this https://www.npmjs.com/package/bower-alternative-source-resolver to help us map different families of components and circumvent the limitations of the shorthand_resolver.

**Comment by sheerun** [comment]
This issue got stale, if it's still an issue, please open another one with steps to reproduce
