### ISSUE TITLE
bower no longer has a user-agent on requests

### ISSUE THREAD

**Issue by patrickkettner** [bower/bower#1958]
as of 0bb1536, bower is no longer sending a user-agent header. Since that doesn't seem to be intentional, can we bring it back?

**Comment by sheerun** [comment]
Why it stopped sending it? I don't see anything in code.

**Comment by pwielgolaski** [comment]
I think this fix it not ideal 
The problem is that after rework in download.js request does not get options that should get.
options from https://github.com/bower/bower/blob/master/lib/core/resolvers/GitHubResolver.js#L74
contains User-Agent & what is more important for me (strictSSL)

I commented this one in https://github.com/bower/bower/commit/0bb1536c9972e13f3be06bea9a8619632966c664#diff-cc6e4c18bd5d43bea297db7c1cb58af8R33

**Comment by pwielgolaski** [comment]
I created pull request for this change #1972
