### ISSUE TITLE
resolutions unnecessary with --save-exact?

### ISSUE THREAD

**Issue by avdd** [bower/bower#1982]
If I keep all my dependencies pinned in bower.json, and update a package with --save-exact to persist the exact version, what's the point of the resolutions field?  It's just noise that I have to remove before committing.

**Comment by sheerun** [comment]
@pertrai1 Please ask for feedback before marking issues as "requires feedback"

**Comment by avdd** [comment]
What?

**Comment by sheerun** [comment]
@prappo Why did you close it?

**Comment by sheerun** [comment]
It's probably because some other package uses exact resolution as well (or at least conflicting one). Currently Bower doesn't automatically favor parent depdnencies from child dependencies, so exact resolution is needed in bower.json. This may be annoying but that's how it works now.

If you feel Bower could do better, please send a PR and make sure this change is 100% backward compatible.
