### ISSUE TITLE
Ignore different directories/files on development/production install

### ISSUE THREAD

**Issue by David-Mulder** [bower/bower#2024]
So, there is a beautiful way to tell bower that we depend on different stuff on production and development, because on development we need more stuff than on production, but why can't we (as far as I know) tell bower to ignore/include different files/directories depending on whether we are in development/production?

To give an extremely common real world example, when developing Web Components it's incredibly common to include a `demo` directory, a directory which one would definitely wish to pull in on development, but not on production. It would be great if we could thus specify files/directories which should only be ignored if `--production`.

**Comment by faceleg** [comment]
Yes, please see: http://stackoverflow.com/a/19341028/187954

**Comment by David-Mulder** [comment]
@faceleg How is that relevant? I know already how `devDependencies` and `dependencies` work, I mention them in the **very first line of my issue** and you close this issue by referencing a stackoverflow answer explaining how they work? Like wt*?

**Comment by faceleg** [comment]
Right, apologies for being blind there

**Comment by faceleg** [comment]
AFAIK there is no way to do this. If you can provide a solid spec and we get agreement that it would be a generally desirable feature then a PR would be appropriate

**Comment by David-Mulder** [comment]
@faceleg: And my apologies for reacting harsher than needed. But isn't the wisest order:

 1. See whether this is a desirable feature
 2. Figure out a solid spec
 3. And only then think about a PR?

Because right now this issue was meant as step 1. I think that in the Polymer/Web Component world  this definitely is something we would love, but I have little perspective on bower usager outside of that context.

**Comment by faceleg** [comment]
@bower/bower-volunteers thoughts?

**Comment by MeTaNoV** [comment]
+1 bower is not dead? :)

**Comment by faceleg** [comment]
It is most certainly not.  http://bower.io/blog/

**Comment by sheerun** [comment]
Currently bower downloads whole repositories, and only removes files afterwards. So ignoring different stuff on production and development doesn't make much sense for saving bandwidth, the caches are also saved in full form, so we don't save much on space either. The only remaining reason to implement it is security, but it's already vulnerability to expose whole bower_components publicly. You should use something like grunt, gulp, or webpack to build appropriate files from bower_components.

It's not a desirable feature, because it gives no benefits, and promotes a bad practice of putting bower_components directly onto production.

**Comment by sheerun** [comment]
Besides you can use something like bower-installer or wiredep if you really need it.

**Comment by David-Mulder** [comment]
@sheerun Shouldn't `devDependencies` be deprecated for the same reason as well then?

**Comment by sheerun** [comment]
On CI/deploy you can do build for production (e.g. without debuggers), and on development you can build for development (e.g. include extra logging library, or testing utilities). You don't need that tools on CI / deploy. That's why there are both `dependencies` and `devDependencies`.

- `dependencies` + `devDependencies` -> development build
- `dependencies` -> production build

The build process is free to ignore any files in both development and production.

**Comment by sheerun** [comment]
(but I think it's far better practice for build processes to whitelist files instead of blacklisting them. it's more secure and reliable way of selecting production assets)

**Comment by David-Mulder** [comment]
@sheerun: Don't you see that's the exact same thing this issue is asking for? You don't need documentation and demo's on production, but you do want them on development. I mean, even if `devDependencies` wouldn't exist your last line is still true:

 > The build process is free to ignore any files or libraries in both development and production.

What we're talking about is purely a convenience method to give package owners control over what is and isn't pulled in. Now, your comment about ignored files actually getting pulled in is quite interesting to be honest, because that's definitely **not** what users are expecting.

**Comment by sheerun** [comment]
If you think you can fix this behavior (removing ignored files only after download), please send a PR. Hint: you can't fix that :)

**Comment by David-Mulder** [comment]
@sheerun: Well, to be honest I don't know much about how bower internally works, but

 1. If it's pulling stuff in through `git` then doing sparse checkouts wouldn't be impossible right? (Really not my area of expertise)
 2. If it really is impossible (which might well be), shouldn't `ignore` get deprecated then? I mean, right now it seems to imply there is functionality that actually does not exist.

**Comment by sheerun** [comment]
1. they are not possible
2. `ignore` is good because it removes files before we create cache for package version on disk. because of it cache takes less space on disk.

**Comment by David-Mulder** [comment]
@sheerun:

 1. Sparse checkouts are definitely possible in `git`. Trying googling it... 
 2. If ignore mean caches take up less space, then it's a good thing if on production one would need to cache even less right?

**Comment by justinfagnani** [comment]
@sheerun: If best practices is to copy files out of `bower_components` into a production folder, which files should be copied? With web components we can at least follow html imports, script tags, and other links, starting from some set of entrypoints, but not everything is statically linked like that. Would everything have to be listed in bower.json/"main", because as far as I can see, most packages do not list every needed asset there.

**Comment by ceoaliongroo** [comment]
I think at the moment, is not necessary define which components or files has to be ignore according the environment.

Mainly because, there are missing a stronger standard on the component structures files as @sheerun said. 

To keep the deploy simple IMHO simple as posible, it's possible prepare the `build` folder (locally is preferible to me) using gulp, grunt, (or other task/build system)... an then following the [yeoman team's recommendation](http://yeoman.io/learning/deployment.html) to add another gulp, grunt task... or do it manually with git ... as you prefer.

At the moment, i see as preferible transfer the responsibility of this to the task/build system.

**Comment by David-Mulder** [comment]
@ceoaliongroo Just want to give some Web Components world perspective to that: In this world there is the expectation that you can just delve into the `bower_components` folder and find the original unmodified code, with comments, demo's, etc. Building is supposed to only happen as the last step in the process. Whilst developing if you see errors one doesn't ever want to end up in minified code. Either way, I think the core point is that there are only two options out there:

 - `ignore` **is** useful, in which case ignoring more on production is a *good* thing and this is desirable
 - `ignore` is **not** useful, in which case it should be deprecated and this addition would be pointless

Now, I am somewhat unsure how useful `ignore` actually is, so I think the potential deprecation of `ignore` should be central to this discussion. After all, I have seen no arguments explaining how `ignore` could be useful, but ignoring more files would be pointless.
