### ISSUE TITLE
Flip Behavior of shallowCloneHosts

### ISSUE THREAD

**Issue by ghost** [bower/bower#2031]
As per https://github.com/bower/bower/commit/26f80d25bef495d66c080e9bd4327f5de96436df enabling shallow cloning of a bower component requires that a `.bowerrc` file exist, and that the file white lists the git repository host.

The change was required because of issues with GitHub Enterprise and RhodeCode (As documented on #1764).

Therefore, projects that are on neither host are required to expend resources training their community to setup a `.bowerrc` file, or add `.bowerrc` files to their projects, because of an issue in a SCM they don't even use.

Therefore, could the behavior be swapped in the next major release of Bower such that shallow cloning, using the HTTP header, is on by default, and that users of misbehaving SCMs must black list their hosts in a `.bowerrc` file?

**Comment by arvindch** [comment]
+1 - I would like to see this, as well, since the misbehaving git hosts are rare, in comparison.

Having `bower` do a full clone for everyone, everytime, by default, seems wasteful.

Thoughts?

**Comment by sheerun** [comment]
We can't break backward compatibility for bower 1.x. This is a breaking change.

We can introduce `--beta` flag or something, though.

**Comment by destroyerofbuilds** [comment]
@sheerun that's why I mentioned a `major` release. I believe this change must wait until the next major release to ensure we don't break any existing workflows.

However, I do believe the behavior should be flipped as part of the next major release. I also believe that users of misbehaving hosts should be expected to disable the shallow clone feature as needed.

Personally, adding `--beta` is only marginally better since it still requires intervention on the part of a developer that wants to take advantage of shallow cloning.

**Comment by sheerun** [comment]
Major release of Bower is not planned anymore
