### ISSUE TITLE
bower link not installing dependencies in version 1.7

### ISSUE THREAD

**Issue by deedubbu** [bower/bower#2097]
Since the update to bower 1.7, the `bower link` command is no longer installing dependencies from the package being linked. I suspect it has to do with commit e3f402fc66ee49e6ca033fdd43ce7a7cf1a5bb0c as the link command calls Project.update which is now only updating specified names and the link command only specifies the project being linked.

**Comment by contolini** [comment]
[Yup.](https://github.com/bower/bower/blob/master/lib/commands/link.js#L62) :+1: It'd be good to get this covered by a regression test before patching it. I'll find some time later today to look into it.

**Comment by BenMann** [comment]
Any updates on this?

**Comment by lbustelo** [comment]
Any updates?

**Comment by kevdez** [comment]
I recreated this issue and everything seems to be working fine. Is there something I'm missing? What is meant by "no longer installing dependencies"? Does this mean it was supposed to add the linked dependency to bower.json?

1. Created two packages: "mypackage" and "otherpackage"
2. `cd mypackage` followed by `bower link`, which creates a global symlink to "mypackage"
3. `cd ../otherpackage` followed by `bower link mypackage`

After this, the "otherpackage" directory had a "bower_components" directory that contained a symlink (shortcut) to "mypackage". If I added a file on the "mypackage" package, it would also appear on the "otherpackage/bower_components/mypackage" dependency, because it was a symlink/shortcut.

**Comment by deedubbu** [comment]
The issue was if "mypackage" declared additional dependency packages in its `bower.json` then when "otherpackage" linked "mypackage", those dependent packages would not get installed into the `bower_components` for "otherpackage".

That being said, it looks like the commit I was blaming (e3f402f) was reverted in commit d3eef577. I've confirmed that in the latest published build (1.7.7) the issue is resolved.
