### ISSUE TITLE
bower command to check which user is currently logged in

### ISSUE THREAD

**Issue by rajzshkr** [bower/bower#2123]
Need a command to check currently logged in user.

Example:
bower whoami 
Currently logged in as ***username***

**Comment by oosidat** [comment]
Do you mean checking for currently logged in user after doing `bower login`?

**Comment by rajzshkr** [comment]
yup, If logged in we have to display the logged in username or have to through info message.

**Comment by oosidat** [comment]
Alright – since we store the username upon login...

[lib/commands/login.js, line 34](https://github.com/bower/bower/blob/master/lib/commands/login.js#L34)
```
configstore.set('username', answers.username);
```
... it should (theoretically) be as simple as getting the username (like [getting the access token in lib/commmands/unregister.js](https://github.com/bower/bower/blob/master/lib/commands/unregister.js#L35)) and printing it to the console.

**Comment by sheerun** [comment]
There's PR for it: #2114 

We can fetch username via received access token, no need for saving username
