### ISSUE TITLE
JS urls without ".js" a the end of the path are saved as "index"

### ISSUE THREAD

**Issue by graingert** [bower/bower#2151]
``` js
{
  ...
  "dependencies": {
    "example": "https://example.com/path/to/js?with-options=in-url"
  }
}
```

results in:

```
.
└── example
    └── index

1 directory, 1 file
```

rather than:

```
.
└── example
    └── index.js

1 directory, 1 file
```

**Comment by graingert** [comment]
Ah this would be fixed by: https://github.com/bower/bower/issues/561#issuecomment-46561041

I could set:
```js
{
  ...
  "dependencies": {
    "example/index.js": "https://example.com/path/to/js?with-options=in-url"
  }
}

**Comment by rajzshkr** [comment]
wip

**Comment by graingert** [comment]
@rajzshkr ?

**Comment by rajzshkr** [comment]
This issue can be achieved by using pluggable resolvers. But Adam ( @sheerun ) is still accepting a PR for this. So I wil be fixing it shortly.

**Comment by graingert** [comment]
@rajzshkr ah thanks, that would be super

**Comment by OmgImAlexis** [comment]
I'm even getting something similar with urls ending in `.js`, if I remove `/blob/master/jquery.elastic.source.js` I get a file called `index` with the html contents and if I add it on I get a files called `index.js` with the same contents. It never downloads the `.js` file.

`bower install --save jquery-elastic="https://github.com/janjarfalk/jquery-elastic/blob/master/jquery.elastic.source.js"`
````
{
  "name": "jquery.elastic.source",
  "_cacheHeaders": {
    "Content-Type": "text/html; charset=utf-8"
  },
  "main": "index.js",
  "_source": "https://github.com/janjarfalk/jquery-elastic/blob/master/jquery.elastic.source.js",
  "_target": "*",
  "_originalSource": "https://github.com/janjarfalk/jquery-elastic/blob/master/jquery.elastic.source.js",
  "_direct": true
}
````

**Comment by graingert** [comment]
You just want to use the github repo for that

**Comment by OmgImAlexis** [comment]
Using just the repo gives the same results but with the html file being used as the contents and a file called index being in the root directory without anything else.

**Comment by graingert** [comment]
you can do `bower install jquery-elastic` now

https://github.com/janjarfalk/jquery-elastic/pull/29

**Comment by graingert** [comment]
What was the command you ran to get this error?
> Using just the repo gives the same results but with the html file being used as the contents and a file called index being in the root directory without anything else.

**Comment by OmgImAlexis** [comment]
I tried all of these and each gave me the same results. I made sure to delete the entry out of the `bower.json` and the directory in `bower_components` before trying with the next one.
````
$ bower install --save "https://github.com/janjarfalk/jquery-elastic"
$ bower install --save "https://github.com/janjarfalk/jquery-elastic/tree/master"
$ bower install --save jquery-elastic="https://github.com/janjarfalk/jquery-elastic/tree/master"
````

**Comment by graingert** [comment]
@OmgImAlexis none of those are the correct invocation. They will all try to download the GitHub webpage.  Read this getting started guide http://bower.io/#install-packages

**Comment by OmgImAlexis** [comment]
Even with `bower install https://github.com/janjarfalk/jquery-elastic/blob/master/jquery.elastic.source.js` I'm getting this though.

That's one of the ways that's listed.

**Comment by graingert** [comment]
@OmgImAlexis that's a URL to the HTML web page describing the JS file.

```
# install the registered package
bower install jquery-elastic
# or install with GitHub short-hand
bower install janjafalk/jquery-elastic
# or if you really want to install with the URL
bower install https://raw.githubusercontent.com/janjarfalk/jquery-elastic/master/jquery.elastic.source.js
```

**Comment by rajzshkr** [comment]
@graingert you are correct, @OmgImAlexis  URL seems to be html page of github, instead you can use **bower install https://raw.githubusercontent.com/janjarfalk/jquery-elastic/master/jquery.elastic.source.js**. This works for me.

**Comment by OmgImAlexis** [comment]
@graingert that should be converted into a usable URL, I don't see why you should have to provide a raw path for it.

**Comment by BenMann** [comment]
This is not an actual issue but intended behaviour.
When you're fetching from GitHub, Bower "knows" that and uses the GitHub resolver, which expects a `bower.json` file (hence the PR by @graingert is a good idea). If you however try installing the raw version from GitHub that will also work and naturally rename it to `index.js`. Again, this is by design and  also discussed in [this old issue](https://github.com/bower/bower/issues/561).   
Just to illustrate: if you try to `bower install http://benmann.de/test.js` this will also result in a file called `index.js` in a folder named `test` > `bower_components/test/index.js`. It's a way of standardization and if you really need to change it, you will have to use a custom resolver.   
That being said, I'm closing this issue (as it is not a real issue).
 If there are further questions please feel free to ask! :)

**Comment by graingert** [comment]
@BenMann I don't think @OmImAlexis 's issue is anything to do with this ticket

**Comment by BenMann** [comment]
@graingert Whoops, you're right. The issue totally changed subject. Let's try to figure this out anyway! :)
Can you provide a (not) working example of this behaviour? I'm not sure if the actual issue is the options you want to provide in the URL or if I'm missing something. I guess you can still use a postintall hooks right now to solve this and just rename the file, in case the URL options are causing this (very likely).

**Comment by BenMann** [comment]
ping @graingert.
I'm still unsure what the options might be useful for — Can you provide an example?

**Comment by sheerun** [comment]
As Bower is deprecated, we encourage now using Yarn for installing packages
