### ISSUE TITLE
v1.7.5 has removed renderers folder

### ISSUE THREAD

**Issue by vernak2539** [bower/bower#2160]
In the latest bower release the `lib/renderers` folder was removed. 

Is there docs for this change so it can be updated in modules which used to use the renderers? And, why was it removed. Just curious?

**Comment by sheerun** [comment]
It wasn't removed. Just moved to sub-directory (lib).

It's because we needed to embed `node_modules` into bower to lock dependencies. If we included it in root directory, earlier versions of npm just removed them. The result is this issue: https://github.com/bower/bower/issues/2152

We decided to wrap all files in extra directory and put node_modules there, so npm leaves them alone.

`lib/renderers` are not part of public Bower API, please don't use them. The only way to use bower programmatically is `require('bower')`.

**Comment by vernak2539** [comment]
@sheerun okay great. Thanks for the update. For some reason I didn't seem them in that folder, but now they're there. Thanks for the update. That all makes sense. Thanks for the great module!

**Comment by sheerun** [comment]
I've released bower 1.7.7 that should have all lib files back at their places
