### ISSUE TITLE
FR: Per-project tokens

### ISSUE THREAD

**Issue by ghost** [bower/bower#2167]
Store per-project tokens in registry, allowing to

```
bower register foo git://bar.com/foo user@example.com
```

and sending that token to the specified email, so the user can later

```
bower login -t <token>
bower unregister foo
```

for any url, not only github ones.

**Comment by BenMann** [comment]
Even though I like the idea, it also has a lot of implications!
While we don't have to care much about security at all right now, this would force us to give some serious thought to protecting those tokens. The reason we are currently using GitHub is also exactly that.. we can just hand off authentication to GitHub and be done with it. Right now that also means other URLs don't get that benefit, as you pointed out. We already know that we don't want to manage users and I'm afraid this is pretty close to doing just that, because in the end it is user-authentication via mail + token. However I'm also interested in more opinions.

**Comment by herby** [comment]
Well, I hardly could come up with something simpler. I explicitly eschewed notion of a "user" so that it is not complicated, so per-project authn which would automtically grant authz; and token + email-to-reset was the least burdensome I could come up with. The email-to-reset could in fact be omitted, but then person registering would need to write the token down and not lose it (what if power outage happens just after registering?) and resets would need to be done by personal communication.

But yes, you would need to have the db of (hashed) tokens and check them. And send emails.

I don't know if there is third party for that (authn/authz for item (hashed) foo and email bar@baz.quux using one-time-token; with no additional strings attached). If there is one, maybe it can be used to offload it and just ask if there is authz or not.

Ben wrote:
> Even though I like the idea, it also has a lot of implications!
> While we don't have to care much about security at all right now,
 this

**Comment by sheerun** [comment]
Unfortunately Bower no longer accepts new features and is in maintenance mode
