### ISSUE TITLE
Doubt about bower cache

### ISSUE THREAD

**Issue by youngwind** [bower/bower#2192]
I want this:
  If a package is already in the cache, install it from cache directly.
  If not, install it from bower.io.
I have tried 
```
bower install [package] --offline
```
but if the package is not in the cache , it will return error instead of install it from bower.io

Npm has modules to do something like this, such as 
1. [npm-proxy-cache](https://www.npmjs.com/package/npm-proxy-cache)
2. [local-npm](https://github.com/nolanlawson/local-npm)
3. [npm-lazy](https://github.com/mixu/npm_lazy)
Is there someting like this?

**Comment by BenMann** [comment]
The Bower cache works just like you described:
`install package` > looks in cache > looks online

Once you have installed a package (resolved online) you can use the `--offline` flag in the future, so that Bower does not resolve the package online, no matter what. In general, when you install a package, it will be cached, so the next installation (given you didn't clear the cache) will automatically use the cached version. Only if there is no cached version, Bower will go and fetch the package online.

Using the `--offline` flag without having installed the package via internet before will result in a `ENOTFOUND` and that is actually intended (as the packages has never been cached and there is no local copy).

If you have further questions, let me know! :dancer:

**Comment by youngwind** [comment]
@BenMann got it, thanks!
