### ISSUE TITLE
Unpublishing bower packages is temporarily disabled

### ISSUE THREAD

**Issue by sheerun** [bower/bower#2210]
Given recent [liberation](https://news.ycombinator.com/item?id=11340510) of multiple packages on npm I have second thoughts about "unpublish" feature of bower's registry. It gives more power to authors' hands but handled irresponsibly it can cause serious security issues. Any of unpublished npm packages could be hijacked and [indeed they have been](https://www.npmjs.com/~nj48).

This is little more dangerous in npm's case because contrary to bower it allows postinstall hooks that one could use to [remove disk content](https://github.com/joaojeronimo/rimrafall), steal ~/.ssh/id_rsa and more. To be honest I'm afraid to install any of my npm projects now (bower is not affected by the way, recent version bundles all dependencies).

I've decided to temporarily disable unpublishing of packages from bower registry and I hope we can have meaningful discussion about future of this feature, and to prevent such situations for bower users.

**Comment by desandro** [comment]
The recent npm incident is an extreme case — lots and lots of packages being unpublished all at once, some with vast usage. However, it is an isolated incident. As a custodian on #120, nearly every unregister request was a reasonable one — either author needed to change the repo, or a package was registered by mistake. I'm more concerned about the workflow if unregistering has to go through the Bower team. It's a large burden to shoulder.

**Comment by pizzapanther** [comment]
Is there anyway to determine a bower package's popularity or usage? And when it hits a certain threshold require approval for an unregister?  I would imagine packages that get registered by accident, have around zero usage and are newer.

**Comment by herby** [comment]
Maybe disallow complete unregistering so name cannot be abused for injecting but allow reregistering. I need to move my packages now, and normally I would just unpublish and publish again. Maybe combine reregistering with email in lieu of #2167.

**Comment by seamys** [comment]
Can I update my mistakes through other means？

**Comment by dvidsilva** [comment]
What about establishing a un-publish window? so that if the author feels that there was an error it can decide to un-publish in an hour or so, but if a package has been downloaded a lot the author won't be able to un-publish. 

Also, namespacing seems to be a great way to avoid those name collisions, not sure if that has been considered yet.

**Comment by herby** [comment]
Unregister is not about fixing error. Unregister / register pair is about moving the url. Allow register over existing old one (and remember it so it can be found when needed) and unregister is not necessary.

Dvid Silva wrote:

**Comment by simison** [comment]
I wrote this at https://github.com/ipmjs/ipmjs/issues/4#issuecomment-200751159:
>I think Wikipedia is a pretty good example of this.
>
>You can't _really_ remove anything from Wikipedia, it just goes to some sort of history/archive. Removing pages goes trough community filters such as voting.
>
>https://en.wikipedia.org/wiki/Wikipedia:Guide_to_deletion
>
>So deletion per-se might not be an issue at NPM, the issue is that rules for it aren't transparent.

**Comment by mosabua** [comment]
Imho treating a release component/package as immutable is a good idea. And that includes it not disappearing to /dev/null .. I would make the unpublishing permanent. The Central Repository has good experience with that working well.

**Comment by softweave** [comment]
I needed to move registered bower packages from my personal repository to a work repository. Because of this injunction, I was forced to register the packages under new names and now am faced with updating all our bower.json files to reference the new name.

**Comment by julmot** [comment]
I'm so happy that Bower gives me the opportunities that npm doesn't. Unpublishing a version for example is impossible in npm. For Bower you just need to delete the tag.  
This is the same for unpublishing a whole package. At the moment I need to change the target (.git) of a package. Therefore I need to unpublish and publish it again. I'm pleased that this function exists and wish that it will be reactivated asap.

**Comment by sheerun** [comment]
I like the ideas:

1. Of restricting unregistering in some way, similarly to Wikipedia
2. Of allowing to move the url to the new endpoint instead unregistering and then registering again

The issue with 1st is that it's entirely new workflow, hard to organize in CLI, and 2nd one would require us to introduce new CLI command to bower, and maintain it.

I think it both cases it would be better if registering / unregistering and moving packages happened through web interface rather than CLI. It would allow us to iterate with higher pace and don't care so much about backward compatibility.

It's also inline with bower's philosophy of vendor-agnostic package management. Currently bower's CLI favores one bower's registry while ideally we should allow to use any registry (npm's, private ones etc.). It also favores github, as "login" feature is only implemented for this service. 

I suggest following:

1. Implement registering / unregistering and moving packages in web interface of registry
2. Deprecate and remove "register", "unregister", and "login" commands in bower's cli
3. Implement additional security measures in web interface of registry

**Comment by julmot** [comment]
@sheerun Could you please describe what exactly you mean in the first point?

Don't you think it's simpler to adjust the already existing CLI commands to fit the two ideas? From my point of view this seems to be less expensive.

**Comment by rajzshkr** [comment]
@sheerun seems to be a great idea. we can implement a web interface, which will make more user-friendly.

**Comment by sheerun** [comment]
I reference what @simison said about wikipedia's process of removing pages.

Modifying CLI commands tend to be little slow, because we need tests for every feature, maintain backward compatibility etc. Iterating on web interface would be faster and would allow for extra features like voting, single-click github login, or easy integration with other vendors.

**Comment by julmot** [comment]
@sheerun I understand you now. However, that didn't changed my opinion. From my point of view the developer who creates packages should have the rights to remove, rename or do whatever he wants with it because he is the owner. And yes, it is crap if you are depending on an open source project that doesn't exist anymore. However, this is open source. If someone decides to drop a package instead of just marking it as "deprecated" (which is btw not possible with Bower) this will have reasons. And as the current situation with @azer shows, the code may be still available on GitHub.

I furthermore don't like the idea to build another social network with a voting feature. If you want to give a repository a star then please do this on GitHub. But I would advocate to have the opportunity to give a GitHub star in the Bower search (web interface). But not as an additional star database...

**Comment by simison** [comment]
@sheerun could you further elaborate possible features/scope of the web interface you were suggesting?
I feel that you @julmot made quite a few assumptions and shortcuts in your comment, particularly with this:
>I furthermore don't like the idea to build another social network with a voting feature. If you want to give a repository a star then please do this on GitHub. But I would advocate to have the opportunity to give a GitHub star in the Bower search (web interface). But not as an additional star database...

— and it's getting harder to follow what actually has been suggested. Cheers!

Remember to keep it polite everyone. ;-)

**Comment by sheerun** [comment]
I never mentioned building social network with voting. Let's forget it until there's clear idea what to implement. My point is to move registry editing tools from cli to web interface, so we can iterate more quickly and become more vendor-independent. Currently it's tied to bower registry and github and every change requires publishing new version of bower while maintaining backward compatibility.

**Comment by herby** [comment]
I am for CLI as well, web interface is limited and interactive, cli is more powerful.

I want to add, consider reallowing unregister (and think of better solutions for the future). Bower is just a register of name to git url; if someone wants to remove access to the project, he can as easily remove it from the git point (and move it to another repo), or at least remove all the semver tags (or garble them not to be semver-compliant). Similar ideas can be done for injecting harmful code.

That said, you may consider remembering the history of all urls registered for a name, so older ones are tried too for versions that newer one does not contain. Plus, again, I would point to #2167 idea of token-per-project which would solve authentication issues (though to complete it, one needs to be able to change the email of the project as well, not just the registered url).

Using history of urls instead of one would, alas, need substantial changes in bower, I am afraid.

**Comment by julmot** [comment]
@herby thanks for that hint. You are right, even if Bower would disallow you from unpublishing, you still could delete the repository. Gotcha!

**Comment by dvidsilva** [comment]
There are a few changes that npm introduced, sure some don't apply to us but it's worth the read. I particularly like their method to prevent squatting. http://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy

**Comment by sheerun** [comment]
Then maybe following:

1. When unpublishing, remove package from search results instead of removing it entirely. This will make existing installations to still work.
2. When registering again, allow only original author to re-register package (the same way only original author can unpublish the package).

**Comment by julmot** [comment]
@sheerun I like the second point. Regarding the first point, if I understand Bower correctly it only caches a repository locally. So trying to download a repository (non-unpublished) that doesn't exist and is not cached locally will not work. This is different to npm where the package with a specific version will be saved on npm. If I am right, why do we discuss about this? Disallowing unpublishing or just with constraints would not prevent you from "hard" unpublishing (Git repository removal).

**Comment by herby** [comment]
@julmot I don't like the @sheerun's second point as it breaks things, unless something like my often cited #2167 is implemented. As I understand it, when I move the repo from github to non-github, I am screwed, as "original author" is one on github, but it won't work for re-registering the moved repo.

**Comment by sheerun** [comment]
As we get more and more valid unregister requests I'm enabling unregistering again, but let's continue the discussion. I see it's hard go achieve a compromise here.

**Comment by herby** [comment]
Start with defining your responsibility. Let's assume you want to stay with lightweight 'just the pointer: registry model, unlike npm-like repository.

In that case your responsibility, IMO, could not be the guarantee of accessibility of the package. The resource you point to can remove versions or the whole repo at its own accord.

In that case, IMO, bower should be just the lightweight registry that points to the resource for the correct version. What could (and maybe should) be improved is twofold: first, allowing publishers do changes as they want to (unregister / reregister also without github account); second, having more data in registry, per-version, to allow use more sources for different versions, to remember commits for the versions, hashes of the whole package etc. to give users clues: this version you obtained is proper version / this version was changed (publisher moved the tag; resolve it somehow) / this version is gone, but knowing commit hash and overall content hash, anyone can offer its copy to revive it.

Yes, it can end up with list of versions and original / moved variations each mapped to different target resource, in the extreme case.

Dňa 31. marca 2016 1:59:22 CEST používateľ Adam Stankiewicz <notifications@github.com> napísal:

**Comment by julmot** [comment]
@herby 

> to remember commits for the versions, hashes of the whole package etc. to give users clues: this version you obtained is proper version / this version was changed (publisher moved the tag; resolve it somehow) / this version is gone, but knowing commit hash and overall content hash, anyone can offer its copy to revive it.

I don't understand you here. If Bower starts to save the latest commit hash under a specific version tag and I would delete and add the version tag again under a newer commit, what would happen in your case?

**Comment by herby** [comment]
That's the question. Bower should signal to clients the version is tampered unless publisher explicitly signals to the registry it was his intention, is my first guess. But yes, this is the part where policy must be found.

Dňa 31. marca 2016 12:47:58 CEST používateľ Julian Motz <notifications@github.com> napísal:

**Comment by julmot** [comment]
@herby But why would anyone delete a tag if it is not his intention?

**Comment by herby** [comment]
Yeah. OK. The simpler, the better.
But then, simplest is how it is now. Good will, no guarantee, single pointer.

Dňa 31. marca 2016 13:19:22 CEST používateľ Julian Motz <notifications@github.com> napísal:

**Comment by herby** [comment]
Another answer to this is: by mistake. Or when reregistering when repo is moved and mistake is done there (then, more tags could be misplaced). IOW, same as git push needs -f when you are rewriting the history.

Julian Motz wrote:

**Comment by shehi** [comment]
Guys, why ```bower login -t TOKEN_HERE``` doesn't work?!

**Comment by gingerlime** [comment]
> having more data in registry, per-version, to allow use more sources for different versions, to remember commits for the versions, hashes of the whole package etc. to give users clues: this version you obtained is proper version / this version was changed (publisher moved the tag; resolve it somehow) / this version is gone, but knowing commit hash and overall content hash, anyone can offer its copy to revive it.

I think the integrity issue shouldn't be underestimated. Even if the package author is not malicious, but, say, decides to overwrite the tag instead of creating a new version, we can end up with two (or more) slightly different packages with the same version... As a package user, this makes my build process completely unreliable. Two builds of the same version can produce different results. (it [just happened to us](https://github.com/rails-assets/rails-assets/issues/326), that's why I ended up here)

**Comment by cmza** [comment]
Gingerlime : I would test new versions of packages by running them through my set of unit tests before allowing them to become part of the live code. This does involve a local(or testing-on-hosted) copy, obviously.  And (here's the chorus) there's some things you just can't test.  But I'd still rather do my best to make sure my code doesn't come crashing down around me -- because I'm the single coder/user and I rely on it for my income -- than not do as much as I can.  If a package has mutated into uselessness or ambiguity or a dogfight (node itself, recently, iirc)...then I have given myself time to look for a replacement or rewriting it myself (in a different language).

**Comment by cmza** [comment]
Gingerlime : Not to imply you're not doing the same thing...re-reading your comment it makes more sense if you are.  But there are noobs who might not...

**Comment by braungoodson** [comment]
What if your company threatens to sue you for publishing a package you wrote for their product "without their consent" ?

**Comment by sheerun** [comment]
@braungoodson It has been re-enabled long time ago. The best solution is probably locking resolved dependencies locally, what needs to be done.
