### ISSUE TITLE
Install fails on finding a version tag with invalid semver

### ISSUE THREAD

**Issue by cudasteve** [bower/bower#2266]
It appears that bower sometimes has issues when trying to install versions of libraries that have invalid semver tags published.  This ticket describes what happened when the UI-Router team forgot a dash in a prerelease tag: https://github.com/angular-ui/ui-router/issues/2500

Here's a stack trace (really messy I know, sorry it was emailed to me), pointing us to right about here: https://github.com/bower/bower/blob/bbc9b35cb1dd7e6c4babe941bbc3b747cee783c6/lib/core/resolvers/GitResolver.js#L209

> "id": "error",
> "level": "error",
> "message": "Invalid Version: 1.0.0alpha0",
> "stacktrace": "TypeError: Invalid Version: 1.0.0alpha0\n at new
> SemVer 
> (<https://deploy.cudasign.com/job/SNAppier_Build_and_Package/ws/SNAppier/n
> ode_modules/bower/lib/node_modules/semver/semver.js>:273:11)\n at
> compare 
> (<https://deploy.cudasign.com/job/SNAppier_Build_and_Package/ws/SNAppier/n
> ode_modules/bower/lib/node_modules/semver/semver.js>:460:10)\n at
> Object.neq 
> (<https://deploy.cudasign.com/job/SNAppier_Build_and_Package/ws/SNAppier/n
> ode_modules/bower/lib/node_modules/semver/semver.js>:504:10)\n at
> GitHubResolver.GitResolver._savePkgMeta
> (<https://deploy.cudasign.com/job/SNAppier_Build_and_Package/ws/SNAppier/n
> ode_modules/bower/lib/core/resolvers/GitResolver.js>:209:56)\n at
> GitHubResolver._savePkgMeta
> (<https://deploy.cudasign.com/job/SNAppier_Build_and_Package/ws/SNAppier/n
> ode_modules/bower/lib/core/resolvers/GitHubResolver.js>:134:53)\n at
> _fulfilled 
> (<https://deploy.cudasign.com/job/SNAppier_Build_and_Package/ws/SNAppier/n
> ode_modules/bower/lib/node_modules/q/q.js>:834:54)\n at
> self.promiseDispatch.done
> (<https://deploy.cudasign.com/job/SNAppier_Build_and_Package/ws/SNAppier/n
> ode_modules/bower/lib/node_modules/q/q.js>:863:30)\n at
> Promise.promise.promiseDispatch
> (<https://deploy.cudasign.com/job/SNAppier_Build_and_Package/ws/SNAppier/n
> ode_modules/bower/lib/node_modules/q/q.js>:796:13)\n at
> <https://deploy.cudasign.com/job/SNAppier_Build_and_Package/ws/SNAppier/no
> de_modules/bower/lib/node_modules/q/q.js>:604:44\n at runSingle
> (<https://deploy.cudasign.com/job/SNAppier_Build_and_Package/ws/SNAppier/n
> ode_modules/bower/lib/node_modules/q/q.js>:137:13)

Expected behavior: bower should just ignore any tags that don't properly parse as semvers.

**Comment by christopherthielen** [comment]
what version of bower are you using?  I was able to `bower install angular-ui-router` without issue (it fetched the 0.3.0 release)

**Comment by cudasteve** [comment]
It was bower 1.7.9 trying to install ui-router ~0.2.17 or 0.2.18.  Unfortunately I just tried locally and I'm not able to reproduce.  It was mostly failing on our build servers, and we've already moved ui-router over to npm to get around it.

From the logs, it looked like it was probably getting tripped up just on parsing the list of versions before it even checked them to see which matched.

Sorry I don't have much more info than that.

**Comment by origicom** [comment]
Don't know if you guys solved this issue already, but I finally found the solution.

root cause of this problem lays in the Git Wrapper that is included in visual studio. Someway this wrapper can't find the version you set in your bower.json and it always installs the latest version (ie. take the master branch instead of the tagged version.

My solution was simple. Install Git for Windows, find the installation bin and remember the path.
Go to visual studio and add this path as an external tool. 

for example:
in Visual Studio go to:  Tools -> Options -> Projects and Solutions -> External Web Tools

Add the location to your Git for Windows bin directory.
ie. c:\program files\Git\bin

Remove the default entry ($(VSINSTALLDIR)\Web\External\git.

if you do a bower install it will finally download the right version and your problem will be solved
