### ISSUE TITLE
Installing components by date

### ISSUE THREAD

**Issue by MrMcGibblets** [bower/bower#2421]
I have checked through the closed issue's and cant find anything but apologies if this is a duplicate and has been discussed previously.

Recently i have had to deal with some repo's that are very active and in "preview" mode and therefore breaking changes can occur fairly often. Bower gives me the ability to install from a specific commit which is fantastic to quickly grab the components from when they were working, however when these components have been split up and have many hard dependencies this becomes a problem, what i would need to do is add each dependency into my bower.json with the commit I want.

I think what would be fantastic (i appreciate it would not be easy to achieve ) would be the ability to pass a date to bower that would use to bring down the components and its dependencies with the last commit before that date.  Would be interested to hear what you all think.

**Comment by sheerun** [comment]
I agree it would be useful if someone managed to implement this. I had similar idea some time ago, but it turned out it would be difficult to implement even for git. For now Bower uses command similar to following to fetch list of available tags: `git ls-remote https://github.com/bower/bower.git`

If you look at the output, there's no information at which time tags were created. It makes it impossible for Bower to select only one version to download .tar archive of, without cloning whole repository. I hope you see the problem.

Any other ideas how to implement it?

**Comment by bundamaryam** [comment]
Bantu saya menyelesaikan masalah ini

**Comment by sheerun** [comment]
Unfortunately Bower is not developed anymore, just maintained, and because of this we won't introduce new features like the one suggested here.
