### ISSUE TITLE
1.8.4 source tarball has changed over time

### ISSUE THREAD

**Issue by fxcoudert** [bower/bower#2527]
See https://github.com/Homebrew/homebrew-core/pull/31767 
The sources at `https://github.com/bower/bower/archive/v1.8.4.tar.gz` have seen their content change: the original SHA-256 checksum of the tarball was `ed4719fa1131dae285de3a013332756ec39f28bc38ec778bc777d74e935163c5` (as recorded in Homebrew at the time we merged the new version), but currently it is `62a6f019638e2a1628d2434a3c62cb62f8d88528fee9abaf6199d203e68cffbc`.

Can you confirm that the file was willingly replaced? I.e. that it is not a malicious change. Thanks!

**Comment by sheerun** [comment]
No, nothing was willingly replaced. I wonder what are the changes

**Comment by sheerun** [comment]
tbh. I thought npm is preventing any changes to already published artifacts. If anything this can be attack on npm side, not bower side :/ i.e. Even if I wanted to, I can't replace this tarball.

**Comment by sheerun** [comment]
Indeed current version has sha256 `62a6f019638e2a1628d2434a3c62cb62f8d88528fee9abaf6199d203e68cffbc` does somebody have old version of this tarball?

**Comment by sheerun** [comment]
Oh I get it, this is github artifact, not npm artifact.

Well I couldn't reproduce sha of old tarball, but there were no changes in repository since I've commited it (all git shas are the same on my computer and in github repository), and there are no changes in tarball compared to 1c15deadc035714a8911a81807ec1e25d6e27683 that was published.

Maybe I might have force pushed tag soon after release because it was on wrong commit (I don't remember it was long time ago), but it seems it's good now.

Hope it helps

**Comment by sheerun** [comment]
or maybe homebrew had wrong sha all along

**Comment by fxcoudert** [comment]
> Maybe I might have force pushed tag soon after release because it was on wrong commit

That's possible.

> or maybe homebrew had wrong sha all along

Our CI doesn't allow to commit a change without the checksums being automatically verified, so that's more unlikely.
