### ISSUE TITLE
What About BowerCDN?

### ISSUE THREAD

**Issue by nullivex** [bower/bower#2546]
Hi!

I could not find a better way to reach out other than IRC, I wanted to see if the project maintainers were interested in working with me on the BowerCDN service. It is located at https://bowercdn.net and works very simple.
* Search a package on bower
* Select a version
* Use CDN URLs

The hosting is done on a redundant server setup and then through a Cloudflare account which I have sponsored since 2013 and will continue to sponsor.

What I would like to do is just attach the CDN service to the project and work with the maintainers to make sure it is operating correctly. Regardless of the state of Bower, I believe these projects continue to serve a useful purpose.

Please let me know your thoughts.

Thank you!

**Comment by sheerun** [comment]
Hello,

We recommend community to focus on one package ecosystem, which admittedly npm's. For this there are already cdn solutions available: https://unpkg.com/

Even then CDN are way of centralising and single point of failure. In fact I think the worst thing about Bower is that it even has a  registry, because it'll stop working as soon as we turn server down.

I've done something like this before: https://rails-assets.org/ and while at the time it seemed a good idea, a far better solution would be to create tool that can install bower packages in rails directly from source (github). Now we need to maintain and pay money for maintaining this CDN.

I'm sorry but personally I'd discourage you to pursue this project. If you still do, best of luck! :)

**Comment by nullivex** [comment]
Thanks for that. Noted.
