### ISSUE TITLE
Install option --minified

### ISSUE THREAD

**Issue by benschwarz** [bower/bower#368]
Once #1 is dealt with, I'd like to propose the following feature: 

`bower install --minify jquery-plugin`

This feature could default to using `main` from component.js, and whether it be css or javascript, be run through YUI / Closure compiler (minification).

This would remove the need to keep compressed files in the repo / package. We would also remove complexity from local build environments. Which would be gnarly.

**Comment by ioquatix** [comment]
I've been thinking about this issue and I wrote a script to assist with using packages installed using bower. I install the packages into a non-public directory and then use the following logic to copy stuff into the site public assets directory:

```ruby
namespace :bower do
	desc 'Load the .bowerrc file and setup the environment for other tasks.'
	task :bowerrc do
		require 'json'
		require 'pathname'
		
		root = Pathname.new(__dir__).dirname
		
		bowerrc_path = root + ".bowerrc"
		bowerrc = JSON.load(File.read(bowerrc_path))
		
		@bower_package_root = root + bowerrc['directory']
		@bower_install_root = root + bowerrc['public']
	end
	
	desc 'Update the bower packages and link into the public directory.'
	task :update => :bowerrc do
		require 'fileutils'
		require 'utopia/path'
		
		#sh %W{bower update}
		
		@bower_package_root.children.select(&:directory?).collect(&:basename).each do |package_directory|
			install_path = @bower_install_root + package_directory
			package_path = @bower_package_root + package_directory
			dist_path = package_path + 'dist'
			
			FileUtils::Verbose.rm_rf install_path
			FileUtils::Verbose.mkpath(install_path.dirname)
			
			# If a package has a dist directory, we only symlink that... otherwise we have to do the entire package, and hope that bower's ignore was setup correctly:
			if File.exist? dist_path
				link_path = Utopia::Path.shortest_path(dist_path, install_path)
			else
				link_path = Utopia::Path.shortest_path(package_path, install_path)
			end
			
			FileUtils::Verbose.ln_s link_path, install_path
		end
	end
end
```

The logic is essentially if a package has a `list` directory, only symlink that, otherwise symlink the entire thing.

I like this approach for our use case. However one thing that could be nice is that 1/ if more people adopted the `dist` directory approach and 2/ because people normally expect bower to install directly into a public assets directory, sometimes the ability to customise packages is a bit limited.

As an example, I've recently been modifying a package, jquery-syntax, to use bower, and support the above model. jquery-syntax has a small build system and generates a lot of files according to the themes you specify. I deploy this now with bower, and it rebuilds in the `dist` directory, so it works really nicely.

Just some ideas :)

**Comment by ioquatix** [comment]
Sorry, if there was one more thing I wanted to add, it would be that standardising on a way to specify the `dist` directory for production would be awesome. For example, in `bower.json` for many packages it would be something like:

```javascript
{
    ...
    "install": "dist"
    ...
}
```

**Comment by manast** [comment]
Ok, so if we just agree that it is not bower's responsibility to provide means to deploy the web app, then the question that follow is: how is it supposed to be used in practice? I mean, for development bower is a beneficial tool, but how is it supposed to be used for production?
Some scenearios I can think of, none of them elegant or convenient:
1) Setup a local static web server to serve the dist directory of *every* dependency (if there is any, since this is not a requirement), and of course not server the rest of the files of every dependency, meaning I need a lot of config in my static server to *only* serve the relevant files. And what if there is no minimized version of the dependency? And everybody knows that static files should be served from a CDN...
2) Implement a build procedure, using gulp/grunt/webpack whatever that picks all the dependencies in the bower components directory and concats/minimized them and put it in a dist directory for the whole app. Issues with this: there is no standard way to know which files should be relevant for the building system since every module is composed of src files, dist files and what not. Also, your references to the dependencies in your index.html needs to be properly updated, can be done, but this is a lot of work.
3) Implement a "search & replace" for all the bower dependencies in your html and replace them by CDN counterparts. Problem is of course not all dependencies exists in CDNs, and you cannot work offline, etc.

Any other ways to accomplish this that does not have big shortcomings?

As it stands now it seems that bower is a tool that makes easy to start development of a web app, postponing the pain of delivering the app to the future, whereas best practice should be, be able to deploy the app into production from the first day of development...

**Comment by sheerun** [comment]
Indeed, you'd probably be better starting with npm/yarn + webpack
