### ISSUE TITLE
Implement 'shrinkwrap' feature

### ISSUE THREAD

**Issue by necolas** [bower/bower#505]
Bower could do with something like npm's shrinkwrap feature to lock down specific versions for deploys.

https://npmjs.org/doc/shrinkwrap.html

This would probably be simpler than what npm has to do, as we'd just need to create a config file to represent the currently installed versions.

Related #416

**Comment by elboletaire** [comment]
:+1:

**Comment by gtrias** [comment]
+1

**Comment by greg0ire** [comment]
Stop "voting" for this feature please. It's already planned, no need to notify everyone on earth.

**Comment by robclancy** [comment]
Haha how is this not implemented. Should be a feature planned from the very start for first release.

**Comment by NgYueHong** [comment]
@greg0ire Happy to see it's already planned. But this has been long talk for over 2 years. When will it be available?

**Comment by greg0ire** [comment]
When the little green bar on the right is full I guess. I don't know I'm not part of the project.

**Comment by sheerun** [comment]
FYI this feature can be theoretically implemented using new [Pluggable Resolvers](http://bower.io/docs/pluggable-resolvers/) feature of Bower.

Review for this PR is still pending, as I have very limited time resources. I hope to convince someone to sponsor work on this feature as it's quite important for Bower's community. Any help is appreciated.

**Comment by Turkish** [comment]
so sad this feature is not yet implemented ...

**Comment by munro** [comment]
Bower has been superseded by npm, just install your dependencies there and use `npm shrinkwrap`

**Comment by greg0ire** [comment]
> Bower has been superseded by npm

Source ?

**Comment by Turkish** [comment]
@munro yes i think you're right, it's useless to have both bower and npm in the same project. Since bower hasn't  'shrinkwrap' it get's superseded by npm naturally thanks for the advice :)

**Comment by robclancy** [comment]
Both bower and npm are bad lol. Bower is understandable as it is just
simple assets and you can commit that crap to a repo for better than
shrinkwrap functionality. But NPM is slow, doesn't cache shit, has very
unclear error messages and yet another package manager without a good
naming scheme so when someone takes a certain name and never updates it can
easily be the proper name for something lost forever.

Our CI is incredibly slow because of npm. All our other package managers
actually cache things and run faster on subsequent builds. And I know there
are 3rd package things to help, they all suck. The only one I haven't done
yet which I am sure will work is the one where it proxys the server (can't
remember the name). Yes, I have to proxy the npm servers just to get basic
functionality all other package managers have so it isn't slow as balls.

Oh and shrinkwrap isn't even good enough. Should lock to exact commits to
get the exact code but it does versions which can easily be broken by
library developers and has twice in the last month for us. Would think the
"omg node is the best thing ever" programmers of the world who would die to
promote it and npm would have a bettter package manager.

**Comment by braincelli** [comment]
https://vid.me/Bratva/albums/sharetheinfo

2015-09-07 23:56 GMT+03:00 Adam Stankiewicz <notifications@github.com>:

**Comment by avindra** [comment]
​I've been thinking about switching full to npm as well. Just nice to have the front end vs. backend package separation. Does npm have any way to specify this in the package.json file?

**Comment by lolmaus** [comment]
>> Bower has been superseded by npm

> Source ?

With Browserify and Babel, I do simply: 

```js
import _ from 'npm:lodash';

_.range(2); // => [0, 1]
```

This works in browsers.

And if a package is not published to npmjs.org, it's possible to install directly from GitHub, optionally asking for a specific tag/release, branch or commit:

    npm install --save-dev user-name/repo-name@v1.0.2

Tell my why I would still need Bower.

**Comment by greg0ire** [comment]
How is this a source ?

**Comment by munro** [comment]
> **robclancy** But NPM is slow

Long off topic rant 😹, but you should post your issue on Stackoverflow, if there truly is an issue with NPM caching it will be a welcomed improvement.  If all else fails use Docker, or NixOS.

> **robclancy** Oh and shrinkwrap isn't even good enough

Shrinkwrap is good enough because developers cannot deploy the same version twice. [1]

[1] https://github.com/npm/npm-registry-couchapp/issues/148

> **avindra** Does npm have any way to specify this in the package.json file?

NPM at this point is just distribution for assets, `webpack` and `browserify` are the mechanisms for compiling on the front end.  There's no standard for "front end" packages, since that's really vague.  There are standards for JavaScript dependencies, so that will just work.  Also `webpack` is very customizable so you can do all sort of crazy things like flat dependencies, or just flat for `lodash` & `jQuery`, or swap them with a CDN, or whatever you can think of!  And then just wrap it in a webpack plugin.

> **greg0ire** How is this a source ?

All the source is here: https://www.npmjs.com/  Give it a try!

**Comment by greg0ire** [comment]
> All the source is here: https://www.npmjs.com/ Give it a try!

What the troll ?

> What I'm waiting for is a link to a blog post from the author of Bower, saying Bower has been superseded by npm. Good luck.

**Comment by lolmaus** [comment]
@greg0ire By any chance, do you move around town via a carriage? You know, because the carriage owner hasn't publish a confirmation that mules have been superseded by automobiles.

**Comment by greg0ire** [comment]
I don't think mules vs automobiles is the same debate as npm vs bower or emacs vs vim. My point is, don't come here stating your personal opinion as a fact. I don't see many carriage users in town, by I know many bower users.

**Comment by munro** [comment]
> **lolmaus**

If only they did, good point that these sort of things happen organically.  I added a small code bounty to this issue a year ago—since then I've just found myself using npm more.  Even in #Node.js they're actively recommending NPM and deterring Bower use, though an article would be nice to make it less confusing for new comers.  Relevancy isn't decided by the project [1], but through hard work one can try to stay relevant [2].

[1] https://github.com/bower/bower/graphs/contributors?from=2014-10-04&to=2015-09-05&type=c
[2] https://github.com/npm/npm/graphs/contributors?from=2014-10-04&to=2015-09-05&type=c

**Comment by jfmercer** [comment]
:+1: for lockfile or similar functionality

**Comment by belka-ew** [comment]
+1 for lockfile

**Comment by mac-u** [comment]
+1 for lockfile

**Comment by PedroSena** [comment]
+1 for lockfile

**Comment by albertinad** [comment]
+1 for lockfile

**Comment by syzer** [comment]
+1

**Comment by lsmith77** [comment]
since it seems like this feature is taking a long time in the making, maybe an intermediate step would be a script living entirely outside of bower? just take a ``bower.json`` file, make a backup copy, traverse what is installed and update the ``bower.json`` file with pinned versions of what is currently installed.

**Comment by syzer** [comment]
@lsmith77 its possible to add custom resolver https://github.com/bower/bower/issues/1649

**Comment by lsmith77** [comment]
see https://github.com/bower/bower/pull/1748

**Comment by dbellettini** [comment]
:+1: for lockfile

**Comment by marco-faustinelli** [comment]
:+1: for lock file

**Comment by twogee** [comment]
is https://github.com/bower/bower/pull/1748 ready for merge?

**Comment by avindra** [comment]
Switched to an npm / webpack setup and haven't looked back. Still working on migrating off bower, because bower is lacking good support for code modularity and dependency locking. I will say that I still like the bower logo though!

**Comment by jpike88** [comment]
+1 for this, come on guys I can't take bower seriously until it has a way of locking down dependency versions, how can you develop with peace of mind without this???

**Comment by Chekote** [comment]
+1

**Comment by MelnikVasya** [comment]
+ 1 for lockfile )

**Comment by avdd** [comment]
Why have a separate lock file when the dependencies can be pinned in bower.json?
But currently it's a pain updating pinned dependencies because `bower update` becomes a no-op, and `bower install` has only one option: --force-latest, otherwise you have to manually check and specify the target version.

**Comment by derrabus** [comment]
@avdd: Like mentioned a couple of times before, you can only pin direct dependencies in bower.json. Indirect/transitive dependencies will always be pulled at their latest compatible version. So pinning in composer.json doesn't cut it.

**Comment by avdd** [comment]
@derrabus I'm not sure what you mean.  Because bower installations are flat and not nested like node, indirect deps become direct deps.  If my app uses Foo which requires Bar, I pin versions of both Foo and Bar in my bower.json, which I believe is the point of the feature under discussion?

**Comment by derrabus** [comment]
@avdd Of course, you can pin the complete dependency graph in your bower.json. But the whole point of a dependency management tool is that you only define your direct dependencies and that it resolves all indirect dependencies for you. What you're describing is a valid workaround, but it's not the solution to the problem.

**Comment by greg0ire** [comment]
@derrabus @avdd ays there is no dependency graph at all : "bower installations are flat". @avdd : what makes you say that ?

**Comment by avdd** [comment]
@greg0ire bower packages are all installed into one bower_components directory at one level, i.e. flat.

@derrabus it's not a workaround at all.  Indirect dependencies are still very much dependencies that should be pinned for repeatable deployments.  The dependency graph as such is only a temporary structure used for installing or updating packages.  Why bother keeping it?

(I assume we can only be talking about top-level projects and not redistributable packages, which clearly have no use for a shrinkwrap feature.)

**Comment by greg0ire** [comment]
>  it's not a workaround at all. Indirect dependencies are still very much dependencies that should be pinned for repeatable deployments.

That's the point of the lock file. On the other hand, when you want to upgrade your top-level dependencies, you don't want to have to find yourself the right version of the indirect deps. That's bower's job, and that's why they should not be kept. Plus if the dependencies have many dependencies that also have dependencies, things could get cumbersome really quickly.

**Comment by davidchin** [comment]
+1 for lockfile

**Comment by benallfree** [comment]
Curious to know if anyone is working on this or what the status is? The lack of lockfile is causing great turbulence on the dev team because they don't want to commit the bower packages to the repo.

**Comment by thiswildorchid** [comment]
+1

**Comment by gitawego** [comment]
+1 for lockfile

**Comment by VaclavDedik** [comment]
+1

**Comment by morrislaptop** [comment]
+1

**Comment by sheerun** [comment]
Please don't +1 this. **We need someone skilled to declare to work at least 1-2 weeks on this feature and then maintain it for some time**, so I can be sure it is solid and stable enough to release. We need to:

1. Review my current requirements about this feature. Do they cover all the edge cases? What are the ramifications? How can we can achieve backward-compatibility and (even more importantly) forward compatibility of this feature (see: current state of shirnkwrap feature of npm...)
2. Review all the initial code of #1748 and make sure everything is properly tested.
3. Implement any changes we agreed on in 1.
4. Test in alpha version with out @bower/contributors 
5. Release it in beta, wait for a feedback
6. **Maintain this feature for some time**

If someone feels competent enough and is interested in this "gig" (Artifactory is eager to pay for time spent on this feature), please post a motivational letter and your availability on my e-mail: sheerun@sher.pl

**Comment by sheerun** [comment]
As Bower is not developed anymore, I'm going to close this issue. There are different solutions available right now, specifically npm has package-lock.json and yarn has yarn.lock. On top of this you can convert your current Bower project to yarn with https://github.com/sheerun/bower-away

It's shame this feature never had production-ready implementation, but oh well, time to move on.
