### ISSUE TITLE
bower install <URL> maps file name to index.js

### ISSUE THREAD

**Issue by gigablox** [bower/bower#561]
`bower install ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.js --save`

But this now maps too an index.js file:
<pre>
"jquery": {
  "source": {
    "main": "vendor/jquery/index.js",
  }
}
</pre>
I want the name of the file to be the the same as in the URL if bower metadata is not available:
<pre>
"jquery": {
  "source": {
    "main": "vendor/jquery/jquery.js",
  }
}
</pre>
http://stackoverflow.com/questions/16577017/use-url-file-name-instead-of-index-js-with-bower

**Comment by Mouvedia** [comment]
That milestone doesn't exist anymore.

**Comment by chasetec** [comment]
I didn't create a proper patch but I did make a fork with the rename to index.js behavior commented out. You can install from:

    npm install -g https://github.com/chasetec/bower/tarball/master

If you are using something like grunt-bower-task that depends on bower you have to fork that package to make it depend on the forked bower version because it doesn't rely on the global version. I made a fork of grunt-bower-task:

    npm install https://github.com/chasetec/grunt-bower-task/tarball/devel --save-dev

**Comment by jdc0589** [comment]
did anything ever happen with this?

**Comment by poppahorse** [comment]
+1

**Comment by Hunga1** [comment]
+1

**Comment by jokerpack-wall-e** [comment]
+1

**Comment by faceleg** [comment]
As per comment https://github.com/bower/bower/issues/561#issuecomment-46561041, a PR for this would be welcome.

**Comment by sheerun** [comment]
Now you can create [pluggable resolver](http://bower.io/docs/pluggable-resolvers/) to achieve it.

I'd still consider accepting a PR for this feature.
