### ISSUE TITLE
Next-gen Bower 'register' and 'publish' commands

### ISSUE THREAD

**Issue by necolas** [bower/bower#579]
Once we have authentication on the server…

**register**

Extracts package name and git endpoint from the `bower.json`. The logged in user would be the owner of the entry in the registry. In the root:

```
bower register
```

To unregister a package owned by an user. From anywhere?

```
bower unregister <name>
```

**publish**

Hosted packages, pass a folder to compress and send to the registry.
This command would require an user to be authenticated. The logged in user would be the owner of the entry in the registry.

```
bower publish <folder>
bower publish <tarball>
```

To unpublish a package owned by an user:

```
bower unpublish <name>
```

We could consider combining register/publish into a single command that knows what to do depending on the type of path?

**Comment by sheerun** [comment]
I think bower this feature is not needed for Bower. NPM does really good job of publishing packages (including front-end ones), and Bower's new [Pluggable Resolvers](http://bower.io/docs/pluggable-resolvers/) feature allows for post-processing fetched packages, including building them on-the-fly or downloading them from custom locations where pre-built versions are present (something like https://www.npmjs.com/package/bower-art-resolver).

You can also create custom resolver that downloads builds from npm instead of github.

Prove me wrong, but for now I'm closing this issue
