### ISSUE TITLE
Bower ignores `directory` setting

### ISSUE THREAD

**Issue by daGrevis** [bower/bower#753]
Hello! 1st time using Bower. :new: 

I want all components to be installed in `static/` directory instead of default `bower_components` directory. I changed `bower.json` a bit, but seems that it doesn't like to get changed. :disappointed:

Here's output of my terminal:

```
 ~/Python/feed_reader % ls static
 ~/Python/feed_reader % cat bower.json
{
    "name": "Very Minimal Feed Reader",
    "version": "0.1",
    "directory": "static/",
    "dependencies": {
        "jquery": "latest"
    }
}
 ~/Python/feed_reader % bower install
bower jquery#*                  cached git://github.com/components/jquery.git#2.0.3
bower jquery#*                validate 2.0.3 against git://github.com/components/jquery.git#*
bower jquery#*                 install jquery#2.0.3

jquery#2.0.3 bower_components/jquery
 ~/Python/feed_reader % ls static
 ~/Python/feed_reader %
```

Any idea why's that?

**Comment by quinncomendant** [comment]
@wibblymat,

> the answer is that bower.json configures your package (for everyone), […]

I'm packaging a web app that will require installing specific bower components into a specific path. I will need to include a `.bowerrc` file, because that is the only place where the **directory** config is honored. I will also need to include a `bower.json` because that is the only place where I can specify **dependencies**. Hence, both files are required when creating a package. That's a little silly.

Is use of *directory* in `bower.json` or *dependencies* in `.bowerrc` on the roadmap?

**Comment by yeelan0319** [comment]
@wibblymat ,

I have exactly the same issue with @quinncomendant . For output directory, it does make a lot sense to think it as a project level configure because it is also how we specify the resource we are going to use. So in my case, I guess my colleague do have a default setting at his parent level's ```.bowerrc``` file and it took me a while to realize that's the reason why it will never work on my computer.

This is the bug that hard to find and at least if bower.json is not going to honor directory setting, it should warn the user that it might cause problem, so it is easier to debug.

Will you think about it as part of the roadmap? Thanks, I really appreciate it if that's something going to happen.

**Comment by Amtrix** [comment]
Started using bower and got confused about this right away. What use-case is there where a specific config is required for one client?

**Comment by azariah001** [comment]
I've encountered this problem and I'm super confused because the guide I found indicated that I just set the directory argument in my bower.json sooooo........ this is still an issue. A big one. The location of the bower_components directory will change project to project and should not be hardcoded just for each user, multiple users may be working on the same project and will inevitably end up with different `.bowerrc` configurations.

**Comment by hamzox** [comment]
I encountered the same problem after cloning a project. What I did after cloning was,
1. bower install
2. npm install 
And other commands.
My custom bower directory was {"directory": "www/lib"}, which wasn't populating dependencies after successfully running bower install.
How did solve the problem?
I cloned the project again and just changed the load order of commands with -g added to npm install.
1. npm install -g
2. bower install
Finally, my www/lib directory was populated with bower dependencies.
