### ISSUE TITLE
Override directory in the command line

### ISSUE THREAD

**Issue by blackjid** [bower/bower#894]
It would be great to be able to override the directory in the command line. Something like in **bundler** where you can do add the `--path  my/path` to specify where to install the directory.

thanks

**Comment by alxdnlnko** [comment]
Hi all. Blackjid is right.
If I specify the absolute path, it must not be relative to the cwd. For example, on production I have a static files folder outside the project, and I want a bower to install its components there. But how can I reach that? I'm trying to specify `"directory": "/static/bower_components"`, but it created the static folder in my project. If I use `"cwd": "/static/"`, bower tries to look for the `bower.json` there and fails, because it is inside the project. It is really strange behaviour and it conficts with common linux rules: if the path starts with '/' it must be used as is.

**Comment by alxdnlnko** [comment]
@satazor Any thoughts?
